CREATE TABLE `characters_json` (
  `guid` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier',
  `account` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Account Identifier',
  `name` VARCHAR(12) NOT NULL DEFAULT '',
  `slot` TINYINT(3) NOT NULL DEFAULT '0',
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `gender` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `xp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `money` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `playerBytes` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `playerBytes2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `playerFlags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `position_x` FLOAT NOT NULL DEFAULT '0',
  `position_y` FLOAT NOT NULL DEFAULT '0',
  `position_z` FLOAT NOT NULL DEFAULT '0',
  `map` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `online` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `totaltime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `leveltime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `logout_time` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `at_login` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `zone` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `totalKills` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `equipmentCache` LONGTEXT,
  `deleteInfos_Account` INT(10) UNSIGNED DEFAULT NULL,
  `deleteInfos_Name` VARCHAR(12) DEFAULT NULL,
  `deleteDate` INT(10) UNSIGNED DEFAULT NULL,
  `transfer` TINYINT(3) NOT NULL DEFAULT '0',
  `guildId` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `transfer_request` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `data` LONGTEXT NOT NULL,
  `mails` LONGTEXT NOT NULL,
  PRIMARY KEY (`guid`),
  KEY `idx_account` (`account`),
  KEY `idx_online` (`online`),
  KEY `idx_name` (`name`),
  KEY `transfer` (`transfer`),
  KEY `guid` (`guid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='Player System';