/*
 * Copyright (C) 2008-2012 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

/// List of Opcodes
enum Opcodes
{
    NUM_OPCODE_HANDLERS                               = (0x7FFF+1),
    UNKNOWN_OPCODE                                    = (0xFFFF+1),
    NULL_OPCODE                                       = 0,
    COMPRESSED_OPCODE_MASK                            = 0x8000,

    CMSG_ACCEPT_LEVEL_GRANT                           = 0x902,  // 5.0.5 16048
    CMSG_ACCEPT_TRADE                                 = 0,
    CMSG_ACTIVATETAXI                                 = 0,
    CMSG_ACTIVATETAXIEXPRESS                          = 0,
    CMSG_ADDON_REGISTERED_PREFIXES                    = 0,
    CMSG_ADD_FRIEND                                   = 0x975,	// 5.0.5 16048
    CMSG_ADD_IGNORE                                   = 0xD48,	// 5.0.5 16048
    CMSG_ADD_VOICE_IGNORE                             = 0,
    CMSG_ALTER_APPEARANCE                             = 0,
    CMSG_AREATRIGGER                                  = 0,
    CMSG_AREA_SPIRIT_HEALER_QUERY                     = 0,
    CMSG_AREA_SPIRIT_HEALER_QUEUE                     = 0,
    CMSG_ARENA_TEAM_ACCEPT                            = 0,
    CMSG_ARENA_TEAM_CREATE                            = 0,
    CMSG_ARENA_TEAM_DECLINE                           = 0,
    CMSG_ARENA_TEAM_DISBAND                           = 0,
    CMSG_ARENA_TEAM_INVITE                            = 0,
    CMSG_ARENA_TEAM_LEADER                            = 0,
    CMSG_ARENA_TEAM_LEAVE                             = 0,
    CMSG_ARENA_TEAM_QUERY                             = 0,
    CMSG_ARENA_TEAM_REMOVE                            = 0,
    CMSG_ARENA_TEAM_ROSTER                            = 0,
    CMSG_ATTACKSTOP                                   = 0x8A7,	// 5.0.5 16048
    CMSG_ATTACKSWING                                  = 0xC40,	// 5.0.5 16048
    CMSG_AUCTION_LIST_BIDDER_ITEMS                    = 0,
    CMSG_AUCTION_LIST_ITEMS                           = 0,
    CMSG_AUCTION_LIST_OWNER_ITEMS                     = 0,
    CMSG_AUCTION_LIST_PENDING_SALES                   = 0,
    CMSG_AUCTION_PLACE_BID                            = 0,
    CMSG_AUCTION_REMOVE_ITEM                          = 0,
    CMSG_AUCTION_SELL_ITEM                            = 0,
    CMSG_AUTH_SESSION                                 = 0x08A,  // 5.0.5 16048
    CMSG_AUTOBANK_ITEM                                = 0,
    CMSG_AUTOEQUIP_GROUND_ITEM                        = 0,
    CMSG_AUTOEQUIP_ITEM                               = 0x888,	// 5.0.5 16048
    CMSG_AUTOEQUIP_ITEM_SLOT                          = 0,
    CMSG_AUTOSTORE_BAG_ITEM                           = 0,
    CMSG_AUTOSTORE_BANK_ITEM                          = 0,
    CMSG_AUTOSTORE_GROUND_ITEM                        = 0,
    CMSG_AUTOSTORE_LOOT_ITEM                          = 0,
    CMSG_AUTO_DECLINE_GUILD_INVITES                   = 0,
    CMSG_BANKER_ACTIVATE                              = 0,
    CMSG_BATTLEFIELD_JOIN                             = 0,
    CMSG_BATTLEFIELD_LEAVE                            = 0x76,	// 5.0.5 16048
    CMSG_BATTLEFIELD_LIST                             = 0,
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE        = 0,
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                 = 0,
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE        = 0,
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST                = 0,
    CMSG_BATTLEFIELD_PORT                             = 0,
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA               = 0,
    CMSG_BATTLEFIELD_STATUS                           = 0,
    CMSG_BATTLEGROUND_PLAYER_POSITIONS                = 0,
    CMSG_BATTLEMASTER_JOIN                            = 0,
    CMSG_BATTLEMASTER_JOIN_ARENA                      = 0,
    CMSG_BATTLEMASTER_JOIN_RATED                      = 0,
    CMSG_BEGIN_TRADE                                  = 0,
    CMSG_BINDER_ACTIVATE                              = 0,
    CMSG_BOT_DETECTED2                                = 0,
    CMSG_BUG                                          = 0,
    CMSG_BUSY_TRADE                                   = 0,
    CMSG_BUYBACK_ITEM                                 = 0,
    CMSG_BUY_BANK_SLOT                                = 0,
    CMSG_BUY_ITEM                                     = 0xD1E,	// 5.0.5 16048
    CMSG_CALENDAR_ADD_EVENT                           = 0,
    CMSG_CALENDAR_ARENA_TEAM                          = 0,
    CMSG_CALENDAR_COMPLAIN                            = 0,
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP                = 0,
    CMSG_CALENDAR_COPY_EVENT                          = 0,
    CMSG_CALENDAR_EVENT_INVITE                        = 0,
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS              = 0,
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                 = 0,
    CMSG_CALENDAR_EVENT_RSVP                          = 0,
    CMSG_CALENDAR_EVENT_SIGNUP                        = 0,
    CMSG_CALENDAR_EVENT_STATUS                        = 0,
    CMSG_CALENDAR_GET_CALENDAR                        = 0,
    CMSG_CALENDAR_GET_EVENT                           = 0,
    CMSG_CALENDAR_GET_NUM_PENDING                     = 0x99A,	// 5.0.5 16048
    CMSG_CALENDAR_GUILD_FILTER                        = 0,
    CMSG_CALENDAR_REMOVE_EVENT                        = 0,
    CMSG_CALENDAR_UPDATE_EVENT                        = 0,
    CMSG_CANCEL_AURA                                  = 0x895,	// 5.0.5 16048
    CMSG_CANCEL_AUTO_REPEAT_SPELL                     = 0,
    CMSG_CANCEL_CAST                                  = 0,
    CMSG_CANCEL_CHANNELLING                           = 0,
    CMSG_CANCEL_GROWTH_AURA                           = 0,
    CMSG_CANCEL_MOUNT_AURA                            = 0,
    CMSG_CANCEL_QUEUED_SPELL                          = 0,
    CMSG_CANCEL_TEMP_ENCHANTMENT                      = 0,
    CMSG_CANCEL_TRADE                                 = 0,
    CMSG_CAST_SPELL                                   = 0x911,	// 5.0.5 16048
    CMSG_CHANGEPLAYER_DIFFICULTY                      = 0,
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE           = 0,
    CMSG_CHANNEL_ANNOUNCEMENTS                        = 0,
    CMSG_CHANNEL_BAN                                  = 0,
    CMSG_CHANNEL_DISPLAY_LIST                         = 0,
    CMSG_CHANNEL_INVITE                               = 0,
    CMSG_CHANNEL_KICK                                 = 0,
    CMSG_CHANNEL_LIST                                 = 0,
    CMSG_CHANNEL_MODERATE                             = 0,
    CMSG_CHANNEL_MODERATOR                            = 0,
    CMSG_CHANNEL_MUTE                                 = 0,
    CMSG_CHANNEL_OWNER                                = 0,
    CMSG_CHANNEL_PASSWORD                             = 0,
    CMSG_CHANNEL_ROSTER_INFO                          = 0,
    CMSG_CHANNEL_SET_OWNER                            = 0,
    CMSG_CHANNEL_SILENCE_ALL                          = 0,
    CMSG_CHANNEL_SILENCE_VOICE                        = 0,
    CMSG_CHANNEL_UNBAN                                = 0,
    CMSG_CHANNEL_UNMODERATOR                          = 0,
    CMSG_CHANNEL_UNMUTE                               = 0,
    CMSG_CHANNEL_UNSILENCE_ALL                        = 0,
    CMSG_CHANNEL_UNSILENCE_VOICE                      = 0,
    CMSG_CHANNEL_VOICE_OFF                            = 0,
    CMSG_CHANNEL_VOICE_ON                             = 0,
    CMSG_CHAR_CREATE                                  = 0x332,  // 5.0.5 16048
    CMSG_CHAR_CUSTOMIZE                               = 0,
    CMSG_CHAR_DELETE                                  = 0x944,  // 5.0.5 16048
    CMSG_CHAR_ENUM                                    = 0x576,  // 5.0.5 16048
    CMSG_CHAR_FACTION_CHANGE                          = 0,
    CMSG_CHAR_RACE_CHANGE                             = 0,
    CMSG_CHAR_RENAME                                  = 0,
    CMSG_CHAT_FILTERED                                = 0,
    CMSG_CHAT_IGNORED                                 = 0,
    CMSG_CLEAR_CHANNEL_WATCH                          = 0,
    CMSG_CLEAR_RAID_MARKER                            = 0,
    CMSG_CLEAR_TRADE_ITEM                             = 0,
    CMSG_COMMENTATOR_ENABLE                           = 0,
    CMSG_COMMENTATOR_ENTER_INSTANCE                   = 0,
    CMSG_COMMENTATOR_EXIT_INSTANCE                    = 0,
    CMSG_COMMENTATOR_GET_MAP_INFO                     = 0,
    CMSG_COMMENTATOR_GET_PARTY_INFO                   = 0,
    CMSG_COMMENTATOR_GET_PLAYER_INFO                  = 0,
    CMSG_COMMENTATOR_INSTANCE_COMMAND                 = 0,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND           = 0,
    CMSG_COMMENTATOR_START_WARGAME                    = 0,
    CMSG_COMPLAIN                                     = 0,
    CMSG_COMPLETE_CINEMATIC                           = 0,
    CMSG_COMPLETE_MOVIE                               = 0,
    CMSG_CONNECT_TO_FAILED                            = 0,
    CMSG_CONTACT_LIST                                 = 0xC80,	// 5.0.5 16048
    CMSG_CORPSE_MAP_POSITION_QUERY                    = 0,
    CMSG_CREATURE_QUERY                               = 0xCA0,  // 5.0.5 16048
    CMSG_DANCE_QUERY                                  = 0,
    CMSG_DECLINE_CHANNEL_INVITE                       = 0,
    CMSG_DELETEEQUIPMENT_SET                          = 0,
    CMSG_DEL_FRIEND                                   = 0x93F,	// 5.0.5 16048
    CMSG_DEL_IGNORE                                   = 0x863,	// 5.0.5 16048
    CMSG_DEL_VOICE_IGNORE                             = 0,
    CMSG_DESTROY_ITEM                                 = 0,
    CMSG_DISMISS_CONTROLLED_VEHICLE                   = 0,
    CMSG_DISMISS_CRITTER                              = 0x87C,	// 5.0.5 16048
    CMSG_DUEL_ACCEPTED                                = 0,
    CMSG_DUEL_CANCELLED                               = 0,
    CMSG_DUNGEON_FINDER_GET_SYSTEM_INFO               = 0x44A,	// 5.0.5 16048
    CMSG_EJECT_PASSENGER                              = 0,
    CMSG_EMOTE                                        = 0xC6C,	// 5.0.5 16048
    CMSG_ENABLETAXI                                   = 0,
    CMSG_ENABLE_NAGLE                                 = 0x3EA,  // 5.0.5 16048
    CMSG_EQUIPMENT_SET_DELETE                         = 0,
    CMSG_EQUIPMENT_SET_SAVE                           = 0,
    CMSG_EQUIPMENT_SET_USE                            = 0,
    CMSG_FAR_SIGHT                                    = 0,
    CMSG_FORCE_MOVE_ROOT_ACK                          = 0,
    CMSG_FORCE_MOVE_UNROOT_ACK                        = 0,
    CMSG_GAMEOBJECT_QUERY                             = 0xCF8,  // 5.0.5 16048
    CMSG_GAMEOBJ_REPORT_USE                           = 0x838,	// 5.0.5 16048
    CMSG_GAMEOBJ_USE                                  = 0xC92,	// 5.0.5 16048
    CMSG_GAMESPEED_SET                                = 0,
    CMSG_GAMETIME_SET                                 = 0,
    CMSG_GETDEATHBINDZONE                             = 0,
    CMSG_GET_MAIL_LIST                                = 0,
    CMSG_GET_MIRRORIMAGE_DATA                         = 0,
    CMSG_GHOST                                        = 0,
    CMSG_GMRESPONSE_RESOLVE                           = 0,
    CMSG_GMSURVEY_SUBMIT                              = 0,
    CMSG_GMTICKET_CREATE                              = 0,
    CMSG_GMTICKET_DELETETICKET                        = 0,
    CMSG_GMTICKET_GETTICKET                           = 0,
    CMSG_GMTICKET_SYSTEMSTATUS                        = 0x925,	// 5.0.5 16048
    CMSG_GMTICKET_UPDATETEXT                          = 0,
    CMSG_GM_INVIS                                     = 0,
    CMSG_GM_NUKE                                      = 0,
    CMSG_GM_REPORT_LAG                                = 0,
    CMSG_GM_SET_SECURITY_GROUP                        = 0,
    CMSG_GOSSIP_HELLO                                 = 0xD7F,	// 5.0.5 16048
    CMSG_GOSSIP_SELECT_OPTION                         = 0,
    CMSG_GRANT_LEVEL                                  = 0,
    CMSG_GROUP_ASSISTANT_LEADER                       = 0,
    CMSG_GROUP_CANCEL                                 = 0,
    CMSG_GROUP_CHANGE_SUB_GROUP                       = 0,
    CMSG_GROUP_DISBAND                                = 0x009,  // 5.0.5 16048
    CMSG_GROUP_INVITE                                 = 0x507,  // 5.0.5 16048
    CMSG_GROUP_INVITE_RESPONSE                        = 0x542,  // 5.0.5 16048
    CMSG_GROUP_RAID_CONVERT                           = 0x34F,  // 5.0.5 16048
    CMSG_GROUP_REQUEST_JOIN_UPDATES                   = 0x744,  // 5.0.5 16048
    CMSG_GROUP_SET_LEADER                             = 0,
    CMSG_GROUP_SET_ROLES                              = 0x302,
    CMSG_GROUP_SWAP_SUB_GROUP                         = 0,
    CMSG_GROUP_UNINVITE                               = 0,
    CMSG_GROUP_UNINVITE_GUID                          = 0x069,
    CMSG_GUILD_ACCEPT                                 = 0,
    CMSG_GUILD_ACHIEVEMENT_MEMBERS                    = 0,
    CMSG_GUILD_ACHIEVEMENT_PROGRESS_QUERY             = 0,
    CMSG_GUILD_ADD_RANK                               = 0,
    CMSG_GUILD_ASSIGN_MEMBER_RANK                     = 0,
    CMSG_GUILD_BANKER_ACTIVATE                        = 0,
    CMSG_GUILD_BANK_BUY_TAB                           = 0,
    CMSG_GUILD_BANK_DEPOSIT_MONEY                     = 0,
    CMSG_GUILD_BANK_LOG_QUERY                         = 0,
    CMSG_GUILD_BANK_MONEY_WITHDRAWN_QUERY             = 0,
    CMSG_GUILD_BANK_NOTE                              = 0,
    CMSG_GUILD_BANK_QUERY_TAB                         = 0,
    CMSG_GUILD_BANK_QUERY_TEXT                        = 0,
    CMSG_GUILD_BANK_SET_TAB_TEXT                      = 0,
    CMSG_GUILD_BANK_SWAP_ITEMS                        = 0,
    CMSG_GUILD_BANK_UPDATE_TAB                        = 0,
    CMSG_GUILD_BANK_WITHDRAW_MONEY                    = 0,
    CMSG_GUILD_CHANGE_NAME_REQUEST                    = 0,
    CMSG_GUILD_DECLINE                                = 0,
    CMSG_GUILD_DEL_RANK                               = 0,
    CMSG_GUILD_DEMOTE                                 = 0,
    CMSG_GUILD_DISBAND                                = 0,
    CMSG_GUILD_EVENT_LOG_QUERY                        = 0,
    CMSG_GUILD_INFO                                   = 0,
    CMSG_GUILD_INFO_TEXT                              = 0,
    CMSG_GUILD_INVITE                                 = 0x306,	// 5.0.5 16048
    CMSG_GUILD_LEADER                                 = 0,
    CMSG_GUILD_LEAVE                                  = 0,
    CMSG_GUILD_MEMBER_SEND_SOR_REQUEST                = 0,
    CMSG_GUILD_MOTD                                   = 0,
    CMSG_GUILD_NEWS_UPDATE_STICKY                     = 0,
    CMSG_GUILD_PERMISSIONS                            = 0,
    CMSG_GUILD_PROMOTE                                = 0,
    CMSG_GUILD_QUERY                                  = 0,
    CMSG_GUILD_QUERY_NEWS                             = 0,
    CMSG_GUILD_QUERY_RANKS                            = 0,
    CMSG_GUILD_REMOVE                                 = 0,
    CMSG_GUILD_REPLACE_GUILD_MASTER                   = 0,
    CMSG_GUILD_REQUEST_CHALLENGE_UPDATE               = 0,
    CMSG_GUILD_REQUEST_MAX_DAILY_XP                   = 0,
    CMSG_GUILD_REQUEST_PARTY_STATE                    = 0,
    CMSG_GUILD_ROSTER                                 = 0,
    CMSG_GUILD_SET_ACHIEVEMENT_TRACKING               = 0x2E7,	// 5.0.5 16048
    CMSG_GUILD_SET_GUILD_MASTER                       = 0,
    CMSG_GUILD_SET_NOTE                               = 0,
    CMSG_GUILD_SET_RANK_PERMISSIONS                   = 0,
    CMSG_GUILD_SWITCH_RANK                            = 0,
    CMSG_HEARTH_AND_RESURRECT                         = 0,
    CMSG_IGNORE_TRADE                                 = 0,
    CMSG_INITIATE_TRADE                               = 0,
    CMSG_INSPECT                                      = 0,
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE               = 0,
    CMSG_ITEM_REFUND                                  = 0,
    CMSG_ITEM_REFUND_INFO                             = 0,
    CMSG_ITEM_TEXT_QUERY                              = 0,
    CMSG_JOIN_CHANNEL                                 = 0x4EC,  // 5.0.5 16048
    CMSG_KEEP_ALIVE                                   = 0x0910,  // 5.0.5 16048
    CMSG_LEARN_PREVIEW_TALENTS                        = 0,
    CMSG_LEARN_PREVIEW_TALENTS_PET                    = 0,
    CMSG_LEARN_TALENT                                 = 0,
    CMSG_LEAVE_BATTLEFIELD                            = 0,
    CMSG_LEAVE_CHANNEL                                = 0,
    CMSG_LFG_GET_PLAYER_INFO                          = 0,
    CMSG_LFG_GET_STATUS                               = 0x04D,	// 5.0.5 16048
    CMSG_LFG_JOIN                                     = 0,
    CMSG_LFG_LEAVE                                    = 0,
    CMSG_LFG_LFR_JOIN                                 = 0,
    CMSG_LFG_LFR_LEAVE                                = 0,
    CMSG_LFG_PARTY_LOCK_INFO_REQUEST                  = 0,
    CMSG_LFG_PROPOSAL_RESULT                          = 0,
    CMSG_LFG_SET_BOOT_VOTE                            = 0,
    CMSG_LFG_SET_COMMENT                              = 0,
    CMSG_LFG_SET_ROLES                                = 0,
    CMSG_LFG_TELEPORT                                 = 0,
    CMSG_LF_GUILD_ADD_RECRUIT                         = 0,
    CMSG_LF_GUILD_BROWSE                              = 0,
    CMSG_LF_GUILD_DECLINE_RECRUIT                     = 0,
    CMSG_LF_GUILD_GET_APPLICATIONS                    = 0,
    CMSG_LF_GUILD_GET_RECRUITS                        = 0,
    CMSG_LF_GUILD_POST_REQUEST                        = 0,
    CMSG_LF_GUILD_REMOVE_RECRUIT                      = 0,
    CMSG_LF_GUILD_SET_GUILD_POST                      = 0,
	CMSG_LF_GUILD_JOIN			                      = 0,
    CMSG_LIST_INVENTORY                               = 0x853,	// 5.0.5 16048
    CMSG_LOAD_SCREEN                                  = 0x060,  // 5.0.5 16048
    CMSG_LOGOUT_CANCEL                                = 0x9E7,  // 5.0.5 16048
    CMSG_LOGOUT_REQUEST                               = 0xCE0,  // 5.0.5 16048
    CMSG_LOG_DISCONNECT                               = 0x48F,  // 5.0.5 16048
    CMSG_LOOT                                         = 0x236,	// 5.0.5 16048
    CMSG_LOOT_CURRENCY                                = 0,
    CMSG_LOOT_MASTER_GIVE                             = 0,
    CMSG_LOOT_METHOD                                  = 0x7F6,  // 5.0.5 16048
    CMSG_LOOT_MONEY                                   = 0,
    CMSG_LOOT_RELEASE                                 = 0,
    CMSG_LOOT_ROLL                                    = 0,
    CMSG_MAIL_CREATE_TEXT_ITEM                        = 0,
    CMSG_MAIL_DELETE                                  = 0,
    CMSG_MAIL_MARK_AS_READ                            = 0,
    CMSG_MAIL_RETURN_TO_SENDER                        = 0,
    CMSG_MAIL_TAKE_ITEM                               = 0,
    CMSG_MAIL_TAKE_MONEY                              = 0,
    CMSG_MEETINGSTONE_INFO                            = 0,
    CMSG_MESSAGECHAT_ADDON_BATTLEGROUND               = 0x584,  // 5.0.5 16048
    CMSG_MESSAGECHAT_ADDON_GUILD                      = 0x11E,  // 5.0.5 16048
    CMSG_MESSAGECHAT_ADDON_OFFICER                    = 0x3ED,  // 5.0.5 16048
    CMSG_MESSAGECHAT_ADDON_PARTY                      = 0x0DE,  // 5.0.5 16048
    CMSG_MESSAGECHAT_ADDON_RAID                       = 0x4A9,  // 5.0.5 16048
    CMSG_MESSAGECHAT_ADDON_WHISPER                    = 0x39F,  // 5.0.5 16048
    CMSG_MESSAGECHAT_AFK                              = 0x384,  // 5.0.5 16048
    CMSG_MESSAGECHAT_BATTLEGROUND                     = 0x4CD,  // 5.0.5 16048
    CMSG_MESSAGECHAT_CHANNEL                          = 0x79A,  // 5.0.5 16048
    CMSG_MESSAGECHAT_DND                              = 0x1EA,  // 5.0.5 16048
    CMSG_MESSAGECHAT_EMOTE                            = 0x285,  // 5.0.5 16048
    CMSG_MESSAGECHAT_GUILD                            = 0x0E4,  // 5.0.5 16048
    CMSG_MESSAGECHAT_OFFICER                          = 0x1C1,  // 5.0.5 16048
    CMSG_MESSAGECHAT_PARTY                            = 0x5A1,  // 5.0.5 16048
    CMSG_MESSAGECHAT_RAID                             = 0x5E8,  // 5.0.5 16048
    CMSG_MESSAGECHAT_RAID_WARNING                     = 0x31F,  // 5.0.5 16048
    CMSG_MESSAGECHAT_SAY                              = 0x61A,  // 5.0.5 16048
    CMSG_MESSAGECHAT_WHISPER                          = 0x0A8,  // 5.0.5 16048
    CMSG_MESSAGECHAT_YELL                             = 0x6E5,  // 5.0.5 16048
    CMSG_MINIGAME_MOVE                                = 0,
    CMSG_MOUNTSPECIAL_ANIM                            = 0,
    CMSG_MOVE_CHARM_TELEPORT_CHEAT                    = 0,
    CMSG_MOVE_CHNG_TRANSPORT                          = 0,
    CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK            = 0,
    CMSG_MOVE_FALL_RESET                              = 0,
    CMSG_MOVE_FEATHER_FALL_ACK                        = 0,
    CMSG_MOVE_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK      = 0,
    CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK           = 0,
    CMSG_MOVE_FORCE_PITCH_RATE_CHANGE_ACK             = 0,
    CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK         = 0,
    CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK              = 0,
    CMSG_MOVE_FORCE_SWIM_BACK_SPEED_CHANGE_ACK        = 0,
    CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK             = 0,
    CMSG_MOVE_FORCE_TURN_RATE_CHANGE_ACK              = 0,
    CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK             = 0,
    CMSG_MOVE_GRAVITY_DISABLE_ACK                     = 0,
    CMSG_MOVE_GRAVITY_ENABLE_ACK                      = 0,
    CMSG_MOVE_HOVER_ACK                               = 0,
    CMSG_MOVE_KNOCK_BACK_ACK                          = 0,
    CMSG_MOVE_NOT_ACTIVE_MOVER                        = 0,
    CMSG_MOVE_SET_CAN_FLY                             = 0,
    CMSG_MOVE_SET_CAN_FLY_ACK                         = 0,
    CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK = 0,
    CMSG_MOVE_SET_COLLISION_HEIGHT_ACK                = 0,
    CMSG_MOVE_SET_RELATIVE_POSITION                   = 0,
    CMSG_MOVE_SET_VEHICLE_REC_ID_ACK                  = 0,
    CMSG_MOVE_SPLINE_DONE                             = 0,
    CMSG_MOVE_TIME_SKIPPED                            = 0x351, // 5.0.5 16048
    CMSG_MOVE_TOGGLE_COLLISION_ACK                    = 0,
    CMSG_MOVE_WATER_WALK_ACK                          = 0,
    CMSG_NAME_QUERY                                   = 0x884,  // 5.0.5 16048
    CMSG_NEW_SPELL_SLOT                               = 0,
    CMSG_NEXT_CINEMATIC_CAMERA                        = 0,
    CMSG_NPC_TEXT_QUERY                               = 0xD1C,	// 5.0.5 16048
    CMSG_OBJECT_UPDATE_FAILED                         = 0,
    CMSG_OBJECT_UPDATE_RESCUED                        = 0,
    CMSG_OFFER_PETITION                               = 0,
    CMSG_OPENING_CINEMATIC                            = 0,
    CMSG_OPEN_ITEM                                    = 0,
    CMSG_OPT_OUT_OF_LOOT                              = 0xD12,
    CMSG_PAGE_TEXT_QUERY                              = 0,
    CMSG_PARTY_SILENCE                                = 0,
    CMSG_PARTY_UNSILENCE                              = 0,
    CMSG_PETITION_BUY                                 = 0,
    CMSG_PETITION_QUERY                               = 0,
    CMSG_PETITION_SHOWLIST                            = 0,
    CMSG_PETITION_SHOW_SIGNATURES                     = 0,
    CMSG_PETITION_SIGN                                = 0,
    CMSG_PET_ABANDON                                  = 0,
    CMSG_PET_ACTION                                   = 0,
    CMSG_PET_CANCEL_AURA                              = 0xC4F,	// 5.0.5 16048
    CMSG_PET_CAST_SPELL                               = 0xCDB,	// 5.0.5 16048
    CMSG_PET_LEARN_TALENT                             = 0,
    CMSG_PET_NAME_CACHE                               = 0,
    CMSG_PET_NAME_QUERY                               = 0x881,	// 5.0.5 16048
    CMSG_PET_RENAME                                   = 0,
    CMSG_PET_SET_ACTION                               = 0,
    CMSG_PET_SPELL_AUTOCAST                           = 0,
    CMSG_PET_STOP_ATTACK                              = 0,
    CMSG_PING                                         = 0x4EB,  // 5.0.5 16048
    CMSG_PLAYED_TIME                                  = 0x9B1,  // 5.0.5 16048
    CMSG_PLAYER_DIFFICULTY_CHANGE                     = 0,
    CMSG_PLAYER_LOGIN                                 = 0x203,  // 5.0.5 16048
    CMSG_PLAYER_LOGOUT                                = 0,
    CMSG_PLAYER_VEHICLE_ENTER                         = 0,
    CMSG_PLAY_DANCE                                   = 0,
    CMSG_PUSHQUESTTOPARTY                             = 0,
    CMSG_PVP_LOG_DATA                                 = 0,
    CMSG_QUERY_BATTLEFIELD_STATE                      = 0,
    CMSG_QUERY_GUILD_MEMBERS_FOR_RECIPE               = 0,
    CMSG_QUERY_GUILD_MEMBER_RECIPES                   = 0,
    CMSG_QUERY_GUILD_RECIPES                          = 0,
    CMSG_QUERY_GUILD_REWARDS                          = 0,
    CMSG_QUERY_GUILD_XP                               = 0,
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                   = 0,
    CMSG_QUERY_QUESTS_COMPLETED                       = 0,
    CMSG_QUERY_TIME                                   = 0xCDA,	// 5.0.5 16048
    CMSG_QUESTGIVER_ACCEPT_QUEST                      = 0,
    CMSG_QUESTGIVER_CANCEL                            = 0,
    CMSG_QUESTGIVER_CHOOSE_REWARD                     = 0,
    CMSG_QUESTGIVER_COMPLETE_QUEST                    = 0,
    CMSG_QUESTGIVER_HELLO                             = 0xD0A,	// 5.0.5 16048
    CMSG_QUESTGIVER_QUERY_QUEST                       = 0xCA1,	// 5.0.5 16048
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                  = 0,
    CMSG_QUESTGIVER_REQUEST_REWARD                    = 0,
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY             = 0xC97,	// 5.0.5 16048
    CMSG_QUESTGIVER_STATUS_QUERY                      = 0xC8D,	// 5.0.5 16048
    CMSG_QUESTLOG_REMOVE_QUEST                        = 0x7F4,	// 5.0.5 16048
    CMSG_QUESTLOG_SWAP_QUEST                          = 0,
    CMSG_QUEST_CONFIRM_ACCEPT                         = 0,
    CMSG_QUEST_NPC_QUERY                              = 0x6FD,	// 5.0.5 16048
    CMSG_QUEST_POI_QUERY                              = 0x8B1,	// 5.0.5 16048
    CMSG_QUEST_QUERY                                  = 0x87F,	// 5.0.5 16048
    CMSG_RAID_LEADER_READY_CHECK                      = 0x709,  // 5.0.5 16048
    CMSG_RAID_CONFIRM_READY_CHECK                     = 0x112,  // 5.0.5 16048
    CMSG_RANDOMIZE_CHAR_NAME                          = 0,
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                 = 0x9A2,  // 5.0.5 16048
    CMSG_READ_ITEM                                    = 0,
    CMSG_REALM_NAME_QUERY                             = 0x81B,  // 5.0.5 16048
    CMSG_REALM_SPLIT                                  = 0x820,  // 5.0.5 16048
    CMSG_RECLAIM_CORPSE                               = 0,
    CMSG_REDIRECTION_AUTH_PROOF                       = 0,
    CMSG_REFORGE_ITEM                                 = 0,
    CMSG_REORDER_CHARACTERS                           = 0,
    CMSG_REPAIR_ITEM                                  = 0x89D,	// 5.0.5 16048
    CMSG_REPLACE_ACCOUNT_DATA                         = 0,
    CMSG_REPOP_REQUEST                                = 0,
    CMSG_REPORT_PVP_AFK                               = 0,
    CMSG_REQUEST_ACCOUNT_DATA                         = 0x9BD,	// 5.0.5 16048
    CMSG_REQUEST_CATEGORY_COOLDOWNS                   = 0x49D,	// 5.0.5 16048
    CMSG_REQUEST_CEMETERY_LIST                        = 0,
    CMSG_REQUEST_HONOR_STATS                          = 0,
    CMSG_REQUEST_HOTFIX                               = 0x643,	// 5.0.5 16048
    CMSG_REQUEST_INSPECT_RATED_BG_STATS               = 0,
    CMSG_REQUEST_PARTY_MEMBER_STATS                   = 0x44E,	// 5.0.5 16048
    CMSG_REQUEST_PET_INFO                             = 0,
    CMSG_REQUEST_PVP_OPTIONS_ENABLED                  = 0x74D,	// 5.0.5 16048
    CMSG_REQUEST_PVP_REWARDS                          = 0,
    CMSG_REQUEST_RAID_INFO                            = 0,
    CMSG_REQUEST_RATED_BG_INFO                        = 0,
    CMSG_REQUEST_RATED_BG_STATS                       = 0,
    CMSG_REQUEST_RESEARCH_HISTORY                     = 0,
    CMSG_REQUEST_VEHICLE_EXIT                         = 0,
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                    = 0,
    CMSG_REQUEST_VEHICLE_PREV_SEAT                    = 0,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                  = 0,
    CMSG_RESET_FACTION_CHEAT                          = 0,
    CMSG_RESET_INSTANCES                              = 0xC71,  // 5.0.5 16048
    CMSG_RESURRECT_RESPONSE                           = 0,
    CMSG_RETURN_TO_GRAVEYARD                          = 0x6D2,	// 5.0.5 16048
    CMSG_ROLE_POLL_BEGIN                              = 0,
    CMSG_SAVE_CUF_PROFILES                            = 0,
    CMSG_SAVE_PLAYER                                  = 0,
    CMSG_SEARCH_LFG_JOIN                              = 0,
    CMSG_SEARCH_LFG_LEAVE                             = 0,
    CMSG_SELF_RES                                     = 0,
    CMSG_SELL_ITEM                                    = 0x997,	// 5.0.5 16048
    CMSG_SEND_MAIL                                    = 0,
    CMSG_SEND_SOR_REQUEST_VIA_ADDRESS                 = 0,
    CMSG_SEND_SOR_REQUEST_VIA_BNET_ACCOUNT_ID         = 0,
    CMSG_SERVERTIME                                   = 0,
    CMSG_SETDEATHBINDPOINT                            = 0,
    CMSG_SETSHEATHED                                  = 0,
    CMSG_SET_ACTIONBAR_TOGGLES                        = 0x8B0,	// 5.0.5 16048
    CMSG_SET_ACTION_BUTTON                            = 0x403,	// 5.0.5 16048
    CMSG_SET_ACTIVE_MOVER                             = 0x4B5,	// 5.0.5 16048
    CMSG_SET_ACTIVE_VOICE_CHANNEL                     = 0,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                    = 0,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                    = 0,
    CMSG_SET_CHANNEL_WATCH                            = 0,
    CMSG_SET_CONTACT_NOTES                            = 0,
    CMSG_SET_CURRENCY_FLAGS                           = 0,
    CMSG_SET_EVERYONE_IS_ASSISTANT                    = 0,
    CMSG_SET_FACTION_ATWAR                            = 0,
    CMSG_SET_FACTION_CHEAT                            = 0,
    CMSG_SET_FACTION_INACTIVE                         = 0,
    CMSG_SET_GUILD_BANK_TEXT                          = 0,
    CMSG_SET_LFG_COMMENT                              = 0,
    CMSG_SET_PET_SLOT                                 = 0,
    CMSG_SET_PLAYER_DECLINED_NAMES                    = 0,
    CMSG_SET_PREFERED_CEMETERY                        = 0,
    CMSG_SET_PRIMARY_TALENT_TREE                      = 0,
    CMSG_SET_RELATIVE_POSITION                        = 0,
    CMSG_SET_SAVED_INSTANCE_EXTEND                    = 0,
    CMSG_SET_SELECTION                                = 0x2B1,	// 5.0.5 16048
    CMSG_SET_SKILL_CHEAT                              = 0,
    CMSG_SET_TAXI_BENCHMARK_MODE                      = 0,
    CMSG_SET_TITLE                                    = 0,
    CMSG_SET_TRADE_CURRENCY                           = 0,
    CMSG_SET_TRADE_GOLD                               = 0,
    CMSG_SET_TRADE_ITEM                               = 0,
    CMSG_SET_VEHICLE_REC_ID_ACK                       = 0,
    CMSG_SET_WATCHED_FACTION                          = 0,
    CMSG_SHOWING_CLOAK                                = 0,
    CMSG_SHOWING_HELM                                 = 0,
    CMSG_SOCKET_GEMS                                  = 0,
    CMSG_SPELLCLICK                                   = 0,
    CMSG_SPIRIT_HEALER_ACTIVATE                       = 0,
    CMSG_SPLIT_ITEM                                   = 0,
    CMSG_STANDSTATECHANGE                             = 0xD96,	// 5.0.5 16048
    CMSG_START_QUEST                                  = 0,
    CMSG_STOP_DANCE                                   = 0,
    CMSG_STORE_LOOT_IN_SLOT                           = 0,
    CMSG_SUBMIT_BUG                                   = 0,
    CMSG_SUBMIT_COMPLAIN                              = 0,
    CMSG_SUGGESTION_SUBMIT                            = 0,
    CMSG_SUMMON_RESPONSE                              = 0,
    CMSG_SUSPEND_TOKEN                                = 0,
    CMSG_SWAP_INV_ITEM                                = 0x810,	// 5.0.5 16048
    CMSG_SWAP_ITEM                                    = 0x89C,	// 5.0.5 16048
    CMSG_SYNC_DANCE                                   = 0,
    CMSG_TAXICLEARALLNODES                            = 0,
    CMSG_TAXIENABLEALLNODES                           = 0,
    CMSG_TAXINODE_STATUS_QUERY                        = 0,
    CMSG_TAXIQUERYAVAILABLENODES                      = 0x93E,	// 5.0.5 16048
    CMSG_TAXISHOWNODES                                = 0,
    CMSG_TELEPORT_TO_UNIT                             = 0,
    CMSG_TEXT_EMOTE                                   = 0x86F,	// 5.0.5 16048
    CMSG_TIME_ADJUSTMENT_RESPONSE                     = 0,
    CMSG_TIME_SYNC_RESP                               = 0x729,	// 5.0.5 16048
    CMSG_TIME_SYNC_RESP_FAILED                        = 0,
    CMSG_TOGGLE_PVP                                   = 0x9D2,
    CMSG_TOTEM_DESTROYED                              = 0,
    CMSG_TRAINER_BUY_SPELL                            = 0,
    CMSG_TRAINER_LIST                                 = 0,
    CMSG_TRANSMOGRIFY_ITEMS                           = 0,
    CMSG_TRIGGER_CINEMATIC_CHEAT                      = 0,
    CMSG_TURN_IN_PETITION                             = 0,
    CMSG_TUTORIAL_CLEAR                               = 0,
    CMSG_TUTORIAL_FLAG                                = 0x924,	// 5.0.5 16048
    CMSG_TUTORIAL_RESET                               = 0,
    CMSG_UNACCEPT_TRADE                               = 0,
    CMSG_UNLEARN_SKILL                                = 0,
    CMSG_UNLEARN_SPECIALIZATION                       = 0,
    CMSG_UNREGISTER_ALL_ADDON_PREFIXES                = 0x71B,	// 5.0.5 16048
    CMSG_UPDATE_ACCOUNT_DATA                          = 0x984,	// 5.0.5 16048
    CMSG_UPDATE_MISSILE_TRAJECTORY                    = 0,
    CMSG_UPDATE_PROJECTILE_POSITION                   = 0,
    CMSG_USED_FOLLOW                                  = 0,
    CMSG_USE_ITEM                                     = 0x9FD,	// 5.0.5 16048
    CMSG_VIOLENCE_LEVEL                               = 0x4B9,	// 5.0.5 16048
    CMSG_VOICE_SESSION_ENABLE                         = 0x937,	// 5.0.5 16048
    CMSG_VOID_STORAGE_QUERY                           = 0,
    CMSG_VOID_STORAGE_TRANSFER                        = 0,
    CMSG_VOID_STORAGE_UNLOCK                          = 0,
    CMSG_VOID_SWAP_ITEM                               = 0,
    CMSG_WARDEN_DATA                                  = 0,
    CMSG_WARGAME_ACCEPT                               = 0,
    CMSG_WARGAME_START                                = 0,
    CMSG_WHO                                          = 0xD69,	// 5.0.5 16048
    CMSG_WHOIS                                        = 0,
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                  = 0xDD0,	// 5.0.5 16048
    CMSG_WORLD_TELEPORT                               = 0,
    CMSG_WRAP_ITEM                                    = 0,
    CMSG_ZONEUPDATE                                   = 0xD3B,	// 5.0.5 16048
    MSG_AUCTION_HELLO                                 = 0,
    MSG_BATTLEGROUND_PLAYER_POSITIONS                 = 0,
    MSG_CHANNEL_START                                 = 0,
    MSG_CHANNEL_UPDATE                                = 0,
    MSG_CORPSE_QUERY                                  = 0,
    MSG_GM_BIND_OTHER                                 = 0,
    MSG_GM_SHOWLABEL                                  = 0,
    MSG_GM_SUMMON                                     = 0,
    MSG_GUILD_BANK_LOG_QUERY                          = 0,
    MSG_GUILD_EVENT_LOG_QUERY                         = 0,
    MSG_INSPECT_ARENA_TEAMS                           = 0x0C75, // 5.0.5 16048
    MSG_LIST_STABLED_PETS                             = 0,
    MSG_MINIMAP_PING                                  = 0x0808, // 5.0.5 16048
    MSG_MOVE_CHARM_TELEPORT_CHEAT                     = 0,
    MSG_MOVE_FALL_LAND                                = 0,
    MSG_MOVE_FEATHER_FALL                             = 0,
    MSG_MOVE_GRAVITY_CHNG                             = 0,
    MSG_MOVE_HEARTBEAT                                = 0,
    MSG_MOVE_HOVER                                    = 0,
    MSG_MOVE_JUMP                                     = 0,
    MSG_MOVE_SET_ALL_SPEED_CHEAT                      = 0,
    MSG_MOVE_SET_COLLISION_HEIGHT                     = 0,
    MSG_MOVE_SET_FACING                               = 0,
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                   = 0,
    MSG_MOVE_SET_PITCH                                = 0,
    MSG_MOVE_SET_RAW_POSITION_ACK                     = 0,
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                 = 0,
    MSG_MOVE_SET_RUN_MODE                             = 0,
    MSG_MOVE_SET_RUN_SPEED_CHEAT                      = 0,
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT                = 0,
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                     = 0,
    MSG_MOVE_SET_TURN_RATE_CHEAT                      = 0,
    MSG_MOVE_SET_WALK_MODE                            = 0,
    MSG_MOVE_SET_WALK_SPEED_CHEAT                     = 0,
    MSG_MOVE_START_ASCEND                             = 0,
    MSG_MOVE_START_BACKWARD                           = 0,
    MSG_MOVE_START_DESCEND                            = 0,
    MSG_MOVE_START_FORWARD                            = 0x3F8,	// 5.0.5 16048
    MSG_MOVE_START_PITCH_DOWN                         = 0,
    MSG_MOVE_START_PITCH_UP                           = 0,
    MSG_MOVE_START_STRAFE_LEFT                        = 0,
    MSG_MOVE_START_STRAFE_RIGHT                       = 0,
    MSG_MOVE_START_SWIM                               = 0,
    MSG_MOVE_START_TURN_LEFT                          = 0,
    MSG_MOVE_START_TURN_RIGHT                         = 0,
    MSG_MOVE_STOP                                     = 0x455,	// 5.0.5 16048
    MSG_MOVE_STOP_ASCEND                              = 0,
    MSG_MOVE_STOP_PITCH                               = 0,
    MSG_MOVE_STOP_STRAFE                              = 0,
    MSG_MOVE_STOP_SWIM                                = 0,
    MSG_MOVE_STOP_TURN                                = 0,
    MSG_MOVE_TELEPORT                                 = 0x0A95, // 5.0.5 16048
    MSG_MOVE_TELEPORT_ACK                             = 0x69D, // 5.0.5 16048
    MSG_MOVE_TELEPORT_CHEAT                           = 0x0A95, // 5.0.5 16048
    MSG_MOVE_TIME_SKIPPED                             = 0x0A52, // 5.0.5 16048
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                   = 0,
    MSG_MOVE_TOGGLE_FALL_LOGGING                      = 0,
    MSG_MOVE_TOGGLE_LOGGING                           = 0,
    MSG_MOVE_UPDATE_CAN_FLY                           = 0,
    MSG_MOVE_UPDATE_FLIGHT_SPEED                      = 0,
    MSG_MOVE_UPDATE_MOUSE                             = 0,
    MSG_MOVE_UPDATE_RUN_SPEED                         = 0,
    MSG_MOVE_UPDATE_TELEPORT                          = 0x0A80, // 5.0.5 16048
    MSG_MOVE_WATER_WALK                               = 0,
    MSG_MOVE_WORLDPORT_ACK                            = 0,
    MSG_NOTIFY_PARTY_SQUELCH                          = 0,
    MSG_PARTY_ASSIGNMENT                              = 0,
    MSG_PETITION_DECLINE                              = 0,
    MSG_PETITION_RENAME                               = 0,
    MSG_PVP_LOG_DATA                                  = 0,
    MSG_QUERY_GUILD_BANK_TEXT                         = 0,
    MSG_QUERY_NEXT_MAIL_TIME                          = 0x97C,	// 5.0.5 16048
    MSG_QUEST_PUSH_RESULT                             = 0x939,	// 5.0.5 16048
    MSG_RAID_TARGET_UPDATE                            = 0xF13,	// 5.0.5 16048
    MSG_RANDOM_ROLL                                   = 0,
    MSG_SAVE_GUILD_EMBLEM                             = 0x0C3D, // 5.0.5 16048
    MSG_SET_DUNGEON_DIFFICULTY                        = 0xD24,  // 5.0.5 16048
    MSG_SET_RAID_DIFFICULTY                           = 0x957,  // 5.0.5 16048
    MSG_START_MOVE_FORWARD                            = 0,
    MSG_TABARDVENDOR_ACTIVATE                         = 0x0C1D, // 5.0.5 16048
    MSG_TALENT_WIPE_CONFIRM                           = 0,
    MSG_VERIFY_CONNECTIVITY                           = 0x4F57, // 5.0.5 16048
    SMSG_ACCOUNT_DATA_TIMES                           = 0xC4B,  // 5.0.5 16048
    SMSG_ACCOUNT_INFO_RESPONSE                        = 0,
    SMSG_ACCOUNT_RESTRICTED_WARNING                   = 0x0B66, // 5.0.5 16048
    SMSG_ACHIEVEMENT_DELETED                          = 0,
    SMSG_ACHIEVEMENT_EARNED                           = 0,
    SMSG_ACTION_BUTTONS                               = 0xE34,  // 5.0.5 16048
    SMSG_ACTIVATETAXIREPLY                            = 0x9DE,	// 5.0.5 16048
    SMSG_ADDON_INFO                                   = 0x9C6,  // 5.0.5 16048
    SMSG_ADD_RUNE_POWER                               = 0,
    SMSG_AI_REACTION                                  = 0x0828, // 5.0.5 16048
    SMSG_ALL_ACHIEVEMENT_DATA                         = 0xB64,  // 5.0.5 16048
    SMSG_AREA_SPIRIT_HEALER_TIME                      = 0,
    SMSG_AREA_TRIGGER_MESSAGE                         = 0,
    SMSG_AREA_TRIGGER_MOVEMENT_UPDATE                 = 0,
    SMSG_ARENA_ERROR                                  = 0,
    SMSG_ARENA_OPPONENT_UPDATE                        = 0x0DA7, // 5.0.5 16048
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED              = 0x9C2,	// 5.0.5 16048
    SMSG_ARENA_TEAM_COMMAND_RESULT                    = 0,
    SMSG_ARENA_TEAM_EVENT                             = 0,
    SMSG_ARENA_TEAM_INVITE                            = 0x0CC9, // 5.0.5 16048
    SMSG_ARENA_TEAM_QUERY_RESPONSE                    = 0,
    SMSG_ARENA_TEAM_ROSTER                            = 0,
    SMSG_ARENA_TEAM_STATS                             = 0x0DD6, // 5.0.5 16048
    SMSG_ATTACKERSTATEUPDATE                          = 0x856,	// 5.0.5 16048
    SMSG_ATTACKSTART                                  = 0x992,	// 5.0.5 16048
    SMSG_ATTACKSTOP                                   = 0x848,	// 5.0.5 16048
    SMSG_ATTACKSWING_BADFACING                        = 0x898,	// 5.0.5 16048
    SMSG_ATTACKSWING_CANT_ATTACK                      = 0x8AC,	// 5.0.5 16048
    SMSG_ATTACKSWING_DEADTARGET                       = 0xC2B,	// 5.0.5 16048
    SMSG_ATTACKSWING_NOTINRANGE                       = 0x852,	// 5.0.5 16048
    SMSG_AUCTION_BIDDER_LIST_RESULT                   = 0,
    SMSG_AUCTION_BIDDER_NOTIFICATION                  = 0,
    SMSG_AUCTION_COMMAND_RESULT                       = 0,
    SMSG_AUCTION_LIST_PENDING_SALES                   = 0,
    SMSG_AUCTION_LIST_RESULT                          = 0,
    SMSG_AUCTION_OWNER_LIST_RESULT                    = 0,
    SMSG_AUCTION_OWNER_NOTIFICATION                   = 0,
    SMSG_AUCTION_REMOVED_NOTIFICATION                 = 0x0882, // 5.0.5 16048
    SMSG_AURACASTLOG                                  = 0,
    SMSG_AURA_POINTS_DEPLETED                         = 0x0BF7, // 5.0.5 16048
    SMSG_AURA_UPDATE                                  = 0x08AB, // 5.0.5 16048
    SMSG_AURA_UPDATE_ALL                              = 0x0DDA, // 5.0.5 16048
    SMSG_AUTH_CHALLENGE                               = 0x523,  // 5.0.5 16048
    SMSG_AUTH_RESPONSE                                = 0xE20,  // 5.0.5 16048
    SMSG_AVAILABLE_VOICE_CHANNEL                      = 0x0941, // 5.0.5 16048
    SMSG_AVERAGE_ITEM_LEVEL_INFORM                    = 0,
    SMSG_BARBER_SHOP_RESULT                           = 0x0835, // 5.0.5 16048
    SMSG_BATTLEFIELD_LIST                             = 0,
    SMSG_BATTLEFIELD_MGR_EJECTED                      = 0x0A89, // 5.0.5 16048
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING                = 0x0B36, // 5.0.5 16048
    SMSG_BATTLEFIELD_MGR_ENTERED                      = 0x0A0A, // 5.0.5 16048
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                 = 0x0B44, // 5.0.5 16048
    SMSG_BATTLEFIELD_MGR_EXIT_REQUEST                 = 0,
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                 = 0,
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE       = 0,
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                 = 0,
    SMSG_BATTLEFIELD_PLAYER_POSITIONS                 = 0,
    SMSG_BATTLEFIELD_PORT_DENIED                      = 0,
    SMSG_BATTLEFIELD_RATED_INFO                       = 0x0A84, // 5.0.5 16048
    SMSG_BATTLEFIELD_STATUS                           = 0,
    SMSG_BATTLEFIELD_STATUS1                          = 0,
    SMSG_BATTLEFIELD_STATUS2                          = 0,
    SMSG_BATTLEFIELD_STATUS3                          = 0,
    SMSG_BATTLEFIELD_STATUS4                          = 0,
    SMSG_BATTLEFIELD_STATUS_FAILED                    = 0,
    SMSG_BATTLEGROUND_INFO_THROTTLED                  = 0x0BEC, // 5.0.5 16048
    SMSG_BATTLEGROUND_PLAYER_JOINED                   = 0x0AB5, // 5.0.5 16048
    SMSG_BATTLEGROUND_PLAYER_LEFT                     = 0x0AD3, // 5.0.5 16048
    SMSG_BATTLEGROUND_PLAYER_POSITIONS                = 0,
    SMSG_BINDER_CONFIRM                               = 0x08CC, // 5.0.5 16048
    SMSG_BINDPOINTUPDATE                              = 0x875,  // 5.0.5 16048
    SMSG_BINDZONEREPLY                                = 0,
    SMSG_BREAK_TARGET                                 = 0,
    SMSG_BUY_BANK_SLOT_RESULT                         = 0,
    SMSG_BUY_FAILED                                   = 0xD16,	// 5.0.5 16048
    SMSG_BUY_ITEM                                     = 0x8E1, // 5.0.5 16048
    SMSG_CALENDAR_ACTION_PENDING                      = 0,
    SMSG_CALENDAR_ARENA_TEAM                          = 0,
    SMSG_CALENDAR_CLEAR_PENDING_ACTION                = 0,
    SMSG_CALENDAR_COMMAND_RESULT                      = 0,
    SMSG_CALENDAR_EVENT_INVITE                        = 0,
    SMSG_CALENDAR_EVENT_INVITE_ALERT                  = 0,
    SMSG_CALENDAR_EVENT_INVITE_NOTES                  = 0,
    SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT            = 0,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED                = 0,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT          = 0,
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT           = 0,
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT        = 0,
    SMSG_CALENDAR_EVENT_REMOVED_ALERT                 = 0,
    SMSG_CALENDAR_EVENT_STATUS                        = 0,
    SMSG_CALENDAR_EVENT_UPDATED_ALERT                 = 0,
    SMSG_CALENDAR_FILTER_GUILD                        = 0,
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                  = 0,
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED                = 0,
    SMSG_CALENDAR_RAID_LOCKOUT_UPDATED                = 0,
    SMSG_CALENDAR_SEND_CALENDAR                       = 0,
    SMSG_CALENDAR_SEND_EVENT                          = 0,
    SMSG_CALENDAR_SEND_NUM_PENDING                    = 0xC29,	// 5.0.5 16048
    SMSG_CALENDAR_UPDATE_INVITE_LIST                  = 0,
    SMSG_CAMERA_SHAKE                                 = 0,
    SMSG_CANCEL_AUTO_REPEAT                           = 0,
    SMSG_CANCEL_COMBAT                                = 0x9D5,	// 5.0.5 16048
    SMSG_CAST_FAILED                                  = 0x91C,	// 5.0.5 16048
    SMSG_CHANNEL_LIST                                 = 0x0CC3, // 5.0.5 16048
    SMSG_CHANNEL_MEMBER_COUNT                         = 0x08D4, // 5.0.5 16048
    SMSG_CHANNEL_NOTIFY                               = 0x91D,	// 5.0.5 16048
    SMSG_CHARACTER_LOGIN_FAILED                       = 0,
    SMSG_CHAR_CREATE                                  = 0xC15,  // 5.0.5 16048
    SMSG_CHAR_CUSTOMIZE                               = 0,
    SMSG_CHAR_DELETE                                  = 0x936,  // 5.0.5 16048
    SMSG_CHAR_ENUM                                    = 0xE28,  // 5.0.5 16048
    SMSG_CHAR_FACTION_CHANGE                          = 0,
    SMSG_CHAR_RENAME                                  = 0,
    SMSG_CHAT_IGNORED_ACCOUNT_MUTED                   = 0x0AC0, // 5.0.5 16048
    SMSG_CHAT_NOT_IN_PARTY                            = 0x0D98, // 5.0.5 16048
    SMSG_CHAT_PLAYER_AMBIGUOUS                        = 0x08EA, // 5.0.5 16048
    SMSG_CHAT_PLAYER_NOT_FOUND                        = 0x08F2, // 5.0.5 16048
    SMSG_CHAT_RESTRICTED                              = 0x0D3C, // 5.0.5 16048
    SMSG_CHAT_SERVER_DISCONNECTED                     = 0,
    SMSG_CHAT_SERVER_RECONNECTED                      = 0x0CC8, // 5.0.5 16048
    SMSG_CHAT_WRONG_FACTION                           = 0,
    SMSG_CHECK_FOR_BOTS                               = 0,
    SMSG_CLEAR_BOSS_EMOTES                            = 0x0B87, // 5.0.5 16048
    SMSG_CLEAR_COOLDOWN                               = 0,
    SMSG_CLEAR_COOLDOWNS                              = 0,
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                    = 0,
    SMSG_CLEAR_TARGET                                 = 0xD0B,	// 5.0.5 16048
    SMSG_CLIENTCACHE_VERSION                          = 0xEB4,  // 5.0.5 16048
    SMSG_CLIENT_CONTROL_UPDATE                        = 0,
    SMSG_COMBAT_EVENT_FAILED                          = 0x9EF,	// 5.0.5 16048
    SMSG_COMBAT_LOG_MULTIPLE                          = 0,
    SMSG_COMMENTATOR_MAP_INFO                         = 0x0C11, // 5.0.5 16048
    SMSG_COMMENTATOR_PARTY_INFO                       = 0x0B06, // 5.0.5 16048
    SMSG_COMMENTATOR_PLAYER_INFO                      = 0,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1           = 0x08AA, // 5.0.5 16048
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2           = 0x0CAD, // 5.0.5 16048
    SMSG_COMMENTATOR_STATE_CHANGED                    = 0,
    SMSG_COMPLAIN_RESULT                              = 0x0872, // 5.0.5 16048
    SMSG_COMPRESSED_ACHIEVEMENT_DATA                  = 0,
    SMSG_COMPRESSED_CHAR_ENUM                         = 0,
    SMSG_COMPRESSED_GUILD_ROSTER                      = 0,
    SMSG_COMPRESSED_MOVES                             = 0x0855, // 5.0.5 16048
    SMSG_COMPRESSED_UPDATE_OBJECT                     = 0,
    SMSG_COMSAT_CONNECT_FAIL                          = 0,
    SMSG_COMSAT_DISCONNECT                            = 0,
    SMSG_COMSAT_RECONNECT_TRY                         = 0,
    SMSG_CONTACT_LIST                                 = 0xDC6,  // 5.0.5 16048
    SMSG_CONVERT_RUNE                                 = 0x0CE9, // 5.0.5 16048
    SMSG_COOLDOWN_CHEAT                               = 0,
    SMSG_COOLDOWN_EVENT                               = 0,
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE           = 0,
    SMSG_CORPSE_NOT_IN_INSTANCE                       = 0,
    SMSG_CORPSE_RECLAIM_DELAY                         = 0,
    SMSG_CREATURE_QUERY_RESPONSE                      = 0x0D6C, // 5.0.5 16048
    SMSG_CRITERIA_DELETED                             = 0,
    SMSG_CRITERIA_UPDATE                              = 0x90D,	// 5.0.5 16048
    SMSG_CROSSED_INEBRIATION_THRESHOLD                = 0x0CAA, // 5.0.5 16048
    SMSG_CURRENCY_LOOT_REMOVED                        = 0,
    SMSG_CURRENCY_LOOT_RESTORED                       = 0,
    SMSG_CUSTOM_LOAD_SCREEN                           = 0x0A5B, // 5.0.5 16048
    SMSG_DAMAGE_CALC_LOG                              = 0,
    SMSG_DAMAGE_DONE_OBSOLETE                         = 0,
    SMSG_DANCE_QUERY_RESPONSE                         = 0x0843, // 5.0.5 16048
    SMSG_DB_REPLY                                     = 0x0B8B, // 5.0.5 16048
    SMSG_DEATH_RELEASE_LOC                            = 0x085E, // 5.0.5 16048
    SMSG_DEBUG_RUNE_REGEN                             = 0,
    SMSG_DEFENSE_MESSAGE                              = 0,
    SMSG_DESTROY_OBJECT                               = 0xD82,	// 5.0.5 16048
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                 = 0,
    SMSG_DIFFERENT_INSTANCE_FROM_PARTY                = 0,
    SMSG_DISENCHANT_CREDIT                            = 0,
    SMSG_DISMOUNT                                     = 0,
    SMSG_DISMOUNTRESULT                               = 0,
    SMSG_DISPEL_FAILED                                = 0,
    SMSG_DISPLAY_GAME_ERROR                           = 0x0A63, // 5.0.5 16048
    SMSG_DONT_AUTO_PUSH_SPELLS_TO_ACTION_BAR          = 0x0BD1, // 5.0.5 16048
    SMSG_DROP_NEW_CONNECTION                          = 0,
    SMSG_DUEL_COMPLETE                                = 0x09F6, // 5.0.5 16048
    SMSG_DUEL_COUNTDOWN                               = 0x0993, // 5.0.5 16048
    SMSG_DUEL_INBOUNDS                                = 0,
    SMSG_DUEL_OUTOFBOUNDS                             = 0,
    CMSG_DUEL_PROPOSED                                = 0x448,	// 5.0.5 16048
    SMSG_DUEL_REQUESTED                               = 0x0C30, // 5.0.5 16048
    SMSG_DUEL_WINNER                                  = 0x0DD1, // 5.0.5 16048
    SMSG_DUMP_RIDE_TICKETS_RESPONSE                   = 0x0BF9, // 5.0.5 16048
    SMSG_DURABILITY_DAMAGE_DEATH                      = 0x0D0C, // 5.0.5 16048
    SMSG_ECHO_PARTY_SQUELCH                           = 0,
    SMSG_EMOTE                                        = 0xC3E, // 5.0.5 16048
    SMSG_ENABLE_BARBER_SHOP                           = 0,
    SMSG_ENCHANTMENTLOG                               = 0,
    SMSG_ENVIRONMENTALDAMAGELOG                       = 0x951,	// 5.0.5 16048
    SMSG_EQUIPMENT_SET_LIST                           = 0x980,  // 5.0.5 16048
    SMSG_EQUIPMENT_SET_SAVED                          = 0x0990, // 5.0.5 16048
    SMSG_EQUIPMENT_SET_USE_RESULT                     = 0x0C52, // 5.0.5 16048
    SMSG_EXPECTED_SPAM_RECORDS                        = 0x0C4D, // 5.0.5 16048
    SMSG_EXPLORATION_EXPERIENCE                       = 0xC38,	// 5.0.5 16048
    SMSG_FAILED_PLAYER_CONDITION                      = 0x0A46, // 5.0.5 16048
    SMSG_FEATURE_SYSTEM_STATUS                        = 0xB5B,  // 5.0.5 16048
    SMSG_FEIGN_DEATH_RESISTED                         = 0,
    SMSG_FISH_ESCAPED                                 = 0,
    SMSG_FISH_NOT_HOOKED                              = 0,
    SMSG_FLIGHT_SPLINE_SYNC                           = 0x0864, // 5.0.5 16048
    SMSG_FLOOD_DETECTED                               = 0,
    SMSG_FORCEACTIONSHOW                              = 0,
    SMSG_FORCED_DEATH_UPDATE                          = 0,
    SMSG_FORCE_DISPLAY_UPDATE                         = 0,
    SMSG_FORCE_SEND_QUEUED_PACKETS                    = 0,
    SMSG_FORCE_SET_VEHICLE_REC_ID                     = 0x0AA7, // 5.0.5 16048
    SMSG_FORGE_MASTER_SET                             = 0,
    SMSG_FRIEND_STATUS                                = 0x0DD4, // 5.0.5 16048
    SMSG_GAMEOBJECT_CUSTOM_ANIM                       = 0xCDC,	// 5.0.5 16048
    SMSG_GAMEOBJECT_DESPAWN_ANIM                      = 0,
    SMSG_GAMEOBJECT_PAGETEXT                          = 0x87D,	// 5.0.5 16048
    SMSG_GAMEOBJECT_QUERY_RESPONSE                    = 0x0D21, // 5.0.5 16048
    SMSG_GAMEOBJECT_RESET_STATE                       = 0,
    SMSG_GAMESPEED_SET                                = 0x0D8F, // 5.0.5 16048
    SMSG_GAMETIME_SET                                 = 0x082E, // 5.0.5 16048
    SMSG_GAMETIME_UPDATE                              = 0x0CE3, // 5.0.5 16048
    SMSG_GAME_EVENT_DEBUG_LOG                         = 0x0BDC, // 5.0.5 16048
    SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT                = 0x0AB7, // 5.0.5 16048
    SMSG_GMRESPONSE_DB_ERROR                          = 0,
    SMSG_GMRESPONSE_RECEIVED                          = 0,
    SMSG_GMRESPONSE_STATUS_UPDATE                     = 0,
    SMSG_GMTICKET_CREATE                              = 0,
    SMSG_GMTICKET_DELETETICKET                        = 0,
    SMSG_GMTICKET_GETTICKET                           = 0,
    SMSG_GMTICKET_SYSTEMSTATUS                        = 0xD1F,	// 5.0.5 16048
    SMSG_GMTICKET_UPDATETEXT                          = 0,
    SMSG_GM_MESSAGECHAT                               = 0,
    SMSG_GM_PLAYER_INFO                               = 0,
    SMSG_GM_TICKET_STATUS_UPDATE                      = 0,
    SMSG_GODMODE                                      = 0,
    SMSG_GOSSIP_COMPLETE                              = 0x0CB6, // 5.0.5 16048
    SMSG_GOSSIP_MESSAGE                               = 0xDE4,	// 5.0.5 16048
    SMSG_GOSSIP_POI                                   = 0x0D70, // 5.0.5 16048
    SMSG_GROUPACTION_THROTTLED                        = 0,
    SMSG_GROUP_CANCEL                                 = 0x84B, // 5.0.5 16048
    SMSG_GROUP_DECLINE                                = 0,
    SMSG_GROUP_DESTROYED                              = 0xD3A,	// 5.0.5 16048
    SMSG_GROUP_INVITE                                 = 0xF68,	// 5.0.5 16048
    SMSG_GROUP_JOINED_BATTLEGROUND                    = 0,
    SMSG_PARTY_UPDATE                                 = 0xB3E,	// 5.0.5 16048
    SMSG_GROUP_SET_LEADER                             = 0,//0xA1A,
    SMSG_GROUP_SET_ROLE                               = 0x0A7B, // 5.0.5 16048
    SMSG_GROUP_UNINVITE                               = 0x8A8, // 5.0.5 16048
    SMSG_GUILD_ACHIEVEMENT_DATA                       = 0,
    SMSG_GUILD_ACHIEVEMENT_DELETED                    = 0x0B46, // 5.0.5 16048
    SMSG_GUILD_ACHIEVEMENT_EARNED                     = 0x0A8E, // 5.0.5 16048
    SMSG_GUILD_ACHIEVEMENT_MEMBERS                    = 0x0A62, // 5.0.5 16048
    SMSG_GUILD_BANK_LIST                              = 0,
    SMSG_GUILD_BANK_LOG_QUERY_RESULTS                 = 0,
    SMSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0,
    SMSG_GUILD_BANK_QUERY_TEXT_RESULTS                = 0,
    SMSG_GUILD_CANCEL                                 = 0,
    SMSG_GUILD_CHALLENGE_COMPLETED                    = 0x0A96, // 5.0.5 16048
    SMSG_GUILD_CHALLENGE_UPDATED                      = 0,
    SMSG_GUILD_CHANGE_NAME_RESULT                     = 0,
    SMSG_GUILD_COMMAND_RESULT                         = 0x0A59, // 5.0.5 16048
    SMSG_GUILD_COMMAND_RESULT_2                       = 0x0A59, // 5.0.5 16048
    SMSG_GUILD_CRITERIA_DATA                          = 0x0A81, // 5.0.5 16048
    SMSG_GUILD_CRITERIA_DELETED                       = 0,
    SMSG_GUILD_DECLINE                                = 0x094F, // 5.0.5 16048
    SMSG_GUILD_EVENT                                  = 0,
    SMSG_GUILD_EVENT_LOG_QUERY                        = 0,
    SMSG_GUILD_FLAGGED_FOR_RENAME                     = 0x0ACD, // 5.0.5 16048
    SMSG_GUILD_INVITE                                 = 0,
    SMSG_GUILD_INVITE_CANCEL                          = 0,
    SMSG_GUILD_KNOWN_RECIPES                          = 0,
    SMSG_GUILD_MAX_DAILY_XP                           = 0x0AAF, // 5.0.5 16048
    SMSG_GUILD_MEMBERS_FOR_RECIPE                     = 0x0A04, // 5.0.5 16048
    SMSG_GUILD_MEMBER_DAILY_RESET                     = 0x0A0C, // 5.0.5 16048
    SMSG_GUILD_MEMBER_RECIPES                         = 0x0BFF, // 5.0.5 16048
    SMSG_GUILD_MEMBER_UPDATE_NOTE                     = 0,
    SMSG_GUILD_MOVE_COMPLETE                          = 0x0B40, // 5.0.5 16048
    SMSG_GUILD_MOVE_STARTING                          = 0x0A76, // 5.0.5 16048
    SMSG_GUILD_NEWS_DELETED                           = 0x0A03, // 5.0.5 16048
    SMSG_GUILD_NEWS_UPDATE                            = 0x0BE7, // 5.0.5 16048
    SMSG_GUILD_PARTY_STATE_RESPONSE                   = 0x0B75, // 5.0.5 16048
    SMSG_GUILD_PERMISSIONS_QUERY_RESULTS              = 0,
    SMSG_GUILD_QUERY_RESPONSE                         = 0,
    SMSG_GUILD_RANK                                   = 0,
    SMSG_GUILD_RANKS_UPDATE                           = 0,
    SMSG_GUILD_RECIPES                                = 0x0B7E, // 5.0.5 16048
    SMSG_GUILD_RENAMED                                = 0,
    SMSG_GUILD_REPUTATION_REACTION_CHANGED            = 0x0BDD, // 5.0.5 16048
    SMSG_GUILD_REPUTATION_WEEKLY_CAP                  = 0,
    SMSG_GUILD_RESET                                  = 0,
    SMSG_GUILD_REWARDS_LIST                           = 0,
    SMSG_GUILD_ROSTER                                 = 0x0BEA, // 5.0.5 16048
    SMSG_GUILD_SET_NOTE                               = 0,
    SMSG_GUILD_TRADESKILL_UPDATE                      = 0,
    SMSG_GUILD_UPDATE_ROSTER                          = 0x0BE4, // 5.0.5 16048
    SMSG_GUILD_XP                                     = 0,
    SMSG_GUILD_XP_GAIN                                = 0,
    SMSG_GUILD_XP_UPDATE                              = 0,
    SMSG_HEALTH_UPDATE                                = 0x0841, // 5.0.5 16048
    SMSG_HIGHEST_THREAT_UPDATE                        = 0x0D1A, // 5.0.5 16048
    SMSG_HOTFIX_INFO                                  = 0xF86,  // 5.0.5 16048
    SMSG_HOTFIX_NOTIFY                                = 0,
    SMSG_INITIALIZE_FACTIONS                          = 0x824,  // 5.0.5 16048
    SMSG_INITIAL_SPELLS                               = 0,      
    SMSG_INIT_CURRENCY                                = 0xAE5,	// 5.0.5 16048
    SMSG_INIT_WORLD_STATES                            = 0x919,	// 5.0.5 16048
    SMSG_INSPECT                                      = 0,
    SMSG_INSPECT_HONOR_STATS                          = 0,
    SMSG_INSPECT_RATED_BG_STATS                       = 0x0B42, // 5.0.5 16048
    SMSG_INSPECT_RESULTS_UPDATE                       = 0,
    SMSG_INSPECT_TALENT                               = 0,
    SMSG_INSTANCE_DIFFICULTY                          = 0,
    SMSG_INSTANCE_LOCK_WARNING_QUERY                  = 0x0DAA, // 5.0.5 16048
    SMSG_INSTANCE_RESET                               = 0,
    SMSG_INSTANCE_RESET_FAILED                        = 0,
    SMSG_INSTANCE_SAVE_CREATED                        = 0,
    SMSG_INVALIDATE_DANCE                             = 0x0D7E, // 5.0.5 16048
    SMSG_INVALIDATE_PLAYER                            = 0x8CA,	// 5.0.5 16048
    SMSG_INVALID_PROMOTION_CODE                       = 0,
    SMSG_INVENTORY_CHANGE_FAILURE                     = 0,
    SMSG_ITEM_ADD_PASSIVE                             = 0,
    SMSG_ITEM_COOLDOWN                                = 0,
    SMSG_ITEM_ENCHANT_TIME_UPDATE                     = 0,
    SMSG_ITEM_EXPIRE_PURCHASE_REFUND                  = 0,
    SMSG_ITEM_PUSH_RESULT                             = 0xF64,	// 5.0.5 16048
    SMSG_ITEM_REFUND_INFO_RESPONSE                    = 0,
    SMSG_ITEM_REFUND_RESULT                           = 0x0B43, // 5.0.5 16048
    SMSG_ITEM_REMOVE_PASSIVE                          = 0x0A19, // 5.0.5 16048
    SMSG_ITEM_SEND_PASSIVE                            = 0,
    SMSG_ITEM_TEXT_QUERY_RESPONSE                     = 0x0CB9, // 5.0.5 16048
    SMSG_ITEM_TIME_UPDATE                             = 0,
    SMSG_JOINED_BATTLEGROUND_QUEUE                    = 0,
    SMSG_KICK_REASON                                  = 0,
    SMSG_LEARNED_DANCE_MOVES                          = 0x8C4,  // 5.0.5 16048
    SMSG_SEND_KNOWN_SPELLS                            = 0xEA3,  // 5.0.5 16048
    SMSG_LEARNED_SPELL                                = 0xBF8,	// 5.0.5 16048
    SMSG_LEVELUP_INFO                                 = 0,
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                     = 0,
    SMSG_LFG_DISABLED                                 = 0,
    SMSG_LFG_JOIN_RESULT                              = 0x0A77, // 5.0.5 16048
    SMSG_LFG_OFFER_CONTINUE                           = 0,
    SMSG_LFG_OPEN_FROM_GOSSIP                         = 0,
    SMSG_LFG_PARTY_INFO                               = 0,
    SMSG_LFG_PLAYER_INFO                              = 0,
    SMSG_LFG_PLAYER_REWARD                            = 0,
    SMSG_LFG_PROPOSAL_UPDATE                          = 0x0AEE, // 5.0.5 16048
    SMSG_LFG_QUEUE_STATUS                             = 0,
    SMSG_LFG_ROLE_CHECK_UPDATE                        = 0,
    SMSG_LFG_ROLE_CHOSEN                              = 0,
    SMSG_LFG_SLOT_INVALID                             = 0x0A40, // 5.0.5 16048
    SMSG_LFG_TELEPORT_DENIED                          = 0,
    SMSG_LFG_UPDATE_LIST                              = 0,
    SMSG_LFG_UPDATE_PARTY                             = 0,
    SMSG_LFG_UPDATE_PLAYER                            = 0,
    SMSG_LFG_UPDATE_SEARCH                            = 0,
    SMSG_LFG_UPDATE_STATUS                            = 0,
    SMSG_LFG_UPDATE_STATUS_NONE                       = 0,
    SMSG_LF_GUILD_APPLICANT_LIST_UPDATED              = 0,
    SMSG_LF_GUILD_APPLICATIONS_LIST_CHANGED           = 0x0A1F, // 5.0.5 16048
    SMSG_LF_GUILD_BROWSE_UPDATED                      = 0,
    SMSG_LF_GUILD_COMMAND_RESULT                      = 0,
    SMSG_LF_GUILD_MEMBERSHIP_LIST_UPDATED             = 0x0AF7, // 5.0.5 16048
    SMSG_LF_GUILD_POST_UPDATED                        = 0,
    SMSG_LF_GUILD_RECRUIT_LIST_UPDATED                = 0x0B1D, // 5.0.5 16048
    SMSG_LIST_INVENTORY                               = 0xFDE,  // 5.0.5 16048
    SMSG_LOAD_CUF_PROFILES                            = 0xFC9,  // 5.0.5 16048
	SMSG_LF_GUILD_SEARCH_RESULT                       = 0,
    SMSG_LOGIN_SETTIMESPEED                           = 0xC33,  // 5.0.5 16048
    SMSG_LOGIN_VERIFY_WORLD                           = 0xD33,  // 5.0.5 16048
    SMSG_LOGOUT_CANCEL_ACK                            = 0x803,  // 5.0.5 16048
    SMSG_LOGOUT_COMPLETE                              = 0x8DA,  // 5.0.5 16048
    SMSG_LOGOUT_RESPONSE                              = 0xD86,  // 5.0.5 16048
    SMSG_LOG_XPGAIN                                   = 0x98A,	// 5.0.5 16048
    SMSG_LOOT_ALL_PASSED                              = 0,
    SMSG_LOOT_CLEAR_MONEY                             = 0,
    SMSG_LOOT_CONTENTS                                = 0x0BFC, // 5.0.5 16048
    SMSG_LOOT_ITEM_NOTIFY                             = 0,
    SMSG_LOOT_LIST                                    = 0,
    SMSG_LOOT_MASTER_LIST                             = 0,
    SMSG_LOOT_MONEY_NOTIFY                            = 0,
    SMSG_LOOT_RELEASE_RESPONSE                        = 0,
    SMSG_LOOT_REMOVED                                 = 0,
    SMSG_LOOT_RESPONSE                                = 0,
    SMSG_LOOT_ROLL                                    = 0,
    SMSG_LOOT_ROLL_WON                                = 0,
    SMSG_LOOT_SLOT_CHANGED                            = 0,
    SMSG_LOOT_START_ROLL                              = 0,
    SMSG_MAIL_LIST_RESULT                             = 0,
    SMSG_MAP_OBJ_EVENTS                               = 0x0BF6, // 5.0.5 16048
    SMSG_MEETINGSTONE_COMPLETE                        = 0x08E0, // 5.0.5 16048
    SMSG_MEETINGSTONE_IN_PROGRESS                     = 0,
    SMSG_MEETINGSTONE_MEMBER_ADDED                    = 0,
    SMSG_MEETINGSTONE_SETQUEUE                        = 0,
    SMSG_MESSAGECHAT                                  = 0xC9F,  // 5.0.5 16048
    SMSG_MESSAGE_BOX                                  = 0x0B2F, // 5.0.5 16048
    SMSG_MINIGAME_SETUP                               = 0,
    SMSG_MINIGAME_STATE                               = 0x0C57, // 5.0.5 16048
    SMSG_MIRRORIMAGE_DATA                             = 0x0DC1, // 5.0.5 16048
    SMSG_MISSILE_CANCEL                               = 0,
    SMSG_MODIFY_COOLDOWN                              = 0,
    SMSG_MONEY_NOTIFY                                 = 0x0B33, // 5.0.5 16048
    SMSG_MONSTER_MOVE                                 = 0x942,	// 5.0.5 16048
    SMSG_MONSTER_MOVE_TRANSPORT                       = 0xC35,	// 5.0.5 16048
    SMSG_MOTD                                         = 0x952,  // 5.0.5 16048
    SMSG_MOUNTRESULT                                  = 0,
    SMSG_MOUNTSPECIAL_ANIM                            = 0,
    SMSG_MOVE_COLLISION_DISABLE                       = 0x0A16, // 5.0.5 16048
    SMSG_MOVE_COLLISION_ENABLE                        = 0,
    SMSG_MOVE_DISABLE_COLLISION                       = 0,
    SMSG_MOVE_DISABLE_GRAVITY                         = 0,
    SMSG_MOVE_ENABLE_COLLISION                        = 0,
    SMSG_MOVE_ENABLE_GRAVITY                          = 0,
    SMSG_MOVE_FEATHER_FALL                            = 0x0AFC, // 5.0.5 16048
    SMSG_MOVE_GRAVITY_DISABLE                         = 0,
    SMSG_MOVE_GRAVITY_ENABLE                          = 0x0BF2, // 5.0.5 16048
    SMSG_MOVE_KNOCK_BACK                              = 0x0A79, // 5.0.5 16048
    SMSG_MOVE_LAND_WALK                               = 0x0B1C, // 5.0.5 16048
    SMSG_MOVE_NORMAL_FALL                             = 0,
    SMSG_MOVE_ROOT                                    = 0,
    SMSG_MOVE_SET_ACTIVE_MOVER                        = 0x0A67, // 5.0.5 16048
    SMSG_MOVE_SET_CAN_FLY                             = 0x0B90, // 5.0.5 16048
    SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x0BA7, // 5.0.5 16048
    SMSG_MOVE_SET_COLLISION_HEIGHT                    = 0,
    SMSG_MOVE_SET_COMPOUND_STATE                      = 0x0A98, // 5.0.5 16048
    SMSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0,
    SMSG_MOVE_SET_FLIGHT_SPEED                        = 0x0A66, // 5.0.5 16048
    SMSG_MOVE_SET_HOVER                               = 0,
    SMSG_MOVE_SET_PITCH_RATE                          = 0,
    SMSG_MOVE_SET_RUN_BACK_SPEED                      = 0x0A24, // 5.0.5 16048
    SMSG_MOVE_SET_RUN_SPEED                           = 0,
    SMSG_MOVE_SET_SWIM_BACK_SPEED                     = 0,
    SMSG_MOVE_SET_SWIM_SPEED                          = 0,
    SMSG_MOVE_SET_TURN_RATE                           = 0,
    SMSG_MOVE_SET_VEHICLE_REC_ID                      = 0,
    SMSG_MOVE_SET_WALK_IN_AIR                         = 0,
    SMSG_MOVE_SET_WALK_SPEED                          = 0x0A23, // 5.0.5 16048
    SMSG_MOVE_UNROOT                                  = 0x0B11, // 5.0.5 16048
    SMSG_MOVE_UNSET_CAN_FLY                           = 0x0BC9, // 5.0.5 16048
    SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x0A28,   // 5.0.5 16048
    SMSG_MOVE_UNSET_HOVER                             = 0,  
    SMSG_MOVE_UNSET_WALK_IN_AIR                       = 0,
    SMSG_MOVE_UPDATE_COLLISION_HEIGHT                 = 0,
    SMSG_MOVE_UPDATE_FLIGHT_BACK_SPEED                = 0x0B2A, // 5.0.5 16048
    SMSG_MOVE_UPDATE_KNOCK_BACK                       = 0x0AF1, // 5.0.5 16048
    SMSG_MOVE_UPDATE_PITCH_RATE                       = 0,
    SMSG_MOVE_UPDATE_RUN_BACK_SPEED                   = 0,
    SMSG_MOVE_UPDATE_SWIM_BACK_SPEED                  = 0x0B24, // 5.0.5 16048
    SMSG_MOVE_UPDATE_SWIM_SPEED                       = 0x0AAE, // 5.0.5 16048
    SMSG_MOVE_UPDATE_TELEPORT                         = 0x0A80, // 5.0.5 16048
    SMSG_MOVE_UPDATE_TURN_RATE                        = 0,
    SMSG_MOVE_UPDATE_WALK_SPEED                       = 0x0B28, // 5.0.5 16048
    SMSG_MOVE_WATER_WALK                              = 0,
    SMSG_MULTIPLE_PACKETS                             = 0x0826,	// 5.0.5 16048
    SMSG_NAME_QUERY_RESPONSE                          = 0xCF9,	// 5.0.5 16048
    SMSG_NEW_TAXI_PATH                                = 0x813,	// 5.0.5 16048
    SMSG_NEW_WORLD                                    = 0xF21,  // 5.0.5 16048
    SMSG_NEW_WORLD_ABORT                              = 0,
    SMSG_NOTIFICATION                                 = 0xE0F,
    SMSG_NOTIFY_DANCE                                 = 0,
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                   = 0x08FA, // 5.0.5 16048
    SMSG_NPC_TEXT_UPDATE                              = 0x080C, // 5.0.5 16048
    SMSG_NPC_WONT_TALK                                = 0,
    SMSG_OFFER_PETITION_ERROR                         = 0,
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA         = 0,
    SMSG_OPEN_CONTAINER                               = 0x844,	// 5.0.5 16048
    SMSG_OPEN_LFG_DUNGEON_FINDER                      = 0x0894, // 5.0.5 16048
    SMSG_OVERRIDE_LIGHT                               = 0,
    SMSG_PAGE_TEXT_QUERY_RESPONSE                     = 0x0CE2, // 5.0.5 16048
    SMSG_PARTYKILLLOG                                 = 0x84A,	// 5.0.5 16048
    SMSG_PARTY_COMMAND_RESULT                         = 0xC2D,	// 5.0.5 16048
    SMSG_PARTY_MEMBER_STATS                           = 0xCBA,	// 5.0.5 16048
    SMSG_PARTY_MEMBER_STATS_FULL                      = 0x912,	// 5.0.5 16048
    SMSG_PAUSE_MIRROR_TIMER                           = 0,
    SMSG_PERIODICAURALOG                              = 0,
    SMSG_PETGODMODE                                   = 0x9F3,	// 5.0.5 16048
    SMSG_PETITION_ALREADY_SIGNED                      = 0x0AA8, // 5.0.5 16048
    SMSG_PETITION_QUERY_RESPONSE                      = 0x0C62, // 5.0.5 16048
    SMSG_PETITION_SHOWLIST                            = 0,
    SMSG_PETITION_SHOW_SIGNATURES                     = 0,
    SMSG_PETITION_SIGN_RESULTS                        = 0,
    SMSG_PET_ACTION_FEEDBACK                          = 0,
    SMSG_PET_ACTION_SOUND                             = 0x0C2A, // 5.0.5 16048
    SMSG_PET_ADDED                                    = 0x0A7F, // 5.0.5 16048
    SMSG_PET_BROKEN                                   = 0,
    SMSG_PET_CAST_FAILED                              = 0,
    SMSG_PET_DISMISS_SOUND                            = 0,
    SMSG_PET_GUIDS                                    = 0,
    SMSG_PET_LEARNED_SPELL                            = 0,
    SMSG_PET_MODE                                     = 0,
    SMSG_PET_NAME_INVALID                             = 0x85B,	// 5.0.5 16048
    SMSG_PET_NAME_QUERY_RESPONSE                      = 0x088E, // 5.0.5 16048
    SMSG_PET_REMOVED_SPELL                            = 0,
    SMSG_PET_RENAMEABLE                               = 0,
    SMSG_PET_SLOT_UPDATED                             = 0x0A1B, // 5.0.5 16048
    SMSG_PET_SPELLS                                   = 0,
    SMSG_PET_TAME_FAILURE                             = 0x08CD, // 5.0.5 16048
    SMSG_PET_UPDATE_COMBO_POINTS                      = 0,
    SMSG_PLAYED_TIME                                  = 0x0D59, // 5.0.5 16048
    SMSG_PLAYERBINDERROR                              = 0,
    SMSG_PLAYERBOUND                                  = 0,
    SMSG_PLAYER_DIFFICULTY_CHANGE                     = 0,
    SMSG_PLAYER_MOVE                                  = 0x0A6F, // 5.0.5 16048
    SMSG_PLAYER_SKINNED                               = 0x08B2, // 5.0.5 16048
    SMSG_PLAYER_UNK_DEAD_ALIVE                        = 0,
    SMSG_PLAYER_VEHICLE_DATA                          = 0x09C1, // 5.0.5 16048
    SMSG_PLAY_DANCE                                   = 0x086C, // 5.0.5 16048
    SMSG_PLAY_MUSIC                                   = 0,
    SMSG_PLAY_OBJECT_SOUND                            = 0,
    SMSG_PLAY_SOUND                                   = 0,
	SMSG_PLAY_ONE_SHOT_ANIM_KIT						  = 0,
    SMSG_PLAY_SPELL_IMPACT                            = 0,
    SMSG_PLAY_SPELL_VISUAL                            = 0x0AE4, // 5.0.5 16048
    SMSG_PLAY_SPELL_VISUAL_KIT                        = 0x0AE4, // 5.0.5 16048
    SMSG_PLAY_TIME_WARNING                            = 0x0817, // 5.0.5 16048
    SMSG_PONG                                         = 0x462,  // 5.0.5 16048
    SMSG_POWER_UPDATE                                 = 0x94A,	// 5.0.5 16048
    SMSG_PRE_RESURRECT                                = 0,
    SMSG_PROCRESIST                                   = 0,
    SMSG_PROPOSE_LEVEL_GRANT                          = 0,
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                 = 0,
    SMSG_PVP_CREDIT                                   = 0,
    SMSG_PVP_LOG_DATA                                 = 0x0B3F, // 5.0.5 16048
    SMSG_PVP_OPTIONS_ENABLED                          = 0x0A09, // 5.0.5 16048
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE              = 0,
    SMSG_QUERY_TIME_RESPONSE                          = 0x935,	// 5.0.5 16048
    SMSG_QUESTGIVER_OFFER_REWARD                      = 0x85C,	// 5.0.5 16048
    SMSG_QUESTGIVER_QUEST_COMPLETE                    = 0x0B98, // 5.0.5 16048
    SMSG_QUESTGIVER_QUEST_DETAILS                     = 0xD4E,	// 5.0.5 16048
    SMSG_QUESTGIVER_QUEST_FAILED                      = 0xD02,	// 5.0.5 16048
    SMSG_QUESTGIVER_QUEST_INVALID                     = 0x8C0,	// 5.0.5 16048
    SMSG_QUESTGIVER_QUEST_LIST                        = 0x877,	// 5.0.5 16048
    SMSG_QUESTGIVER_REQUEST_ITEMS                     = 0x8EE,	// 5.0.5 16048
    SMSG_QUESTGIVER_STATUS                            = 0xDB8,	// 5.0.5 16048
    SMSG_QUESTGIVER_STATUS_MULTIPLE                   = 0xD6D,	// 5.0.5 16048
    SMSG_QUESTLOG_FULL                                = 0xC54,	// 5.0.5 16048
    SMSG_QUESTUPDATE_ADD_ITEM                         = 0,
    SMSG_QUESTUPDATE_ADD_KILL                         = 0xC63,	// 5.0.5 16048
    SMSG_QUESTUPDATE_ADD_PVP_KILL                     = 0xD3F,	// 5.0.5 16048
    SMSG_QUESTUPDATE_COMPLETE                         = 0x9B0,	// 5.0.5 16048
    SMSG_QUESTUPDATE_FAILED                           = 0x9F8,	// 5.0.5 16048
    SMSG_QUESTUPDATE_FAILEDTIMER                      = 0,
    SMSG_QUEST_NPC_QUERY_RESPONSE                     = 0x0A2E, // 5.0.5 16048
    SMSG_QUEST_CONFIRM_ACCEPT                         = 0x09D1, // 5.0.5 16048
    SMSG_QUEST_FORCE_REMOVE                           = 0x0D76, // 5.0.5 16048
    SMSG_QUEST_POI_QUERY_RESPONSE                     = 0x950,	// 5.0.5 16048
    SMSG_QUEST_QUERY_RESPONSE                         = 0xD5D,	// 5.0.5 16048
    SMSG_RAID_GROUP_ONLY                              = 0x0DA4, // 5.0.5 16048
    SMSG_RAID_INSTANCE_INFO                           = 0,
    SMSG_RAID_INSTANCE_MESSAGE                        = 0,
    SMSG_RAID_MARKERS_CHANGED                         = 0x0BAA, // 5.0.5 16048
    SMSG_RAID_READY_CHECK_COMPLETED                   = 0xA13,  // 5.0.5 16048
    SMSG_RAID_READY_CHECK_RESPONSE                    = 0xBDE,  // 5.0.5 16048
    SMSG_RAID_READY_CHECK_STARTED                     = 0xF28,  // 5.0.5 16048 
    SMSG_RAID_READY_CHECK_THROTTLED_ERROR             = 0,
    SMSG_RAID_SUMMON_FAILED                           = 0x0A4E, // 5.0.5 16048
    SMSG_RANDOMIZE_CHAR_NAME                          = 0x0A9B, // 5.0.5 16048
    SMSG_RATED_BG_RATING                              = 0x0A4B, // 5.0.5 16048
    SMSG_RATED_BG_STATS                               = 0x0B21, // 5.0.5 16048
    SMSG_READ_ITEM_FAILED                             = 0x086D, // 5.0.5 16048
    SMSG_READ_ITEM_OK                                 = 0,
    SMSG_REALM_QUERY_RESPONSE                         = 0xC26,	// 5.0.5 16048
    SMSG_REALM_SPLIT                                  = 0xCCD,  // 5.0.5 16048
    SMSG_REAL_GROUP_UPDATE                            = 0,
    SMSG_RECEIVED_MAIL                                = 0x08D7, // 5.0.5 16048
    SMSG_REDIRECT_CLIENT                              = 0,
    SMSG_REFER_A_FRIEND_EXPIRED                       = 0,
    SMSG_REFER_A_FRIEND_FAILURE                       = 0,
    SMSG_REFORGE_RESULT                               = 0x0BA6, // 5.0.5 16048
    SMSG_REMOVED_SPELL                                = 0,
    SMSG_REPORT_PVP_AFK_RESULT                        = 0,
    SMSG_REQUEST_CEMETERY_LIST_RESPONSE               = 0x0BB7, // 5.0.5 16048
    SMSG_REQUEST_PVP_REWARDS_RESPONSE                 = 0,
    SMSG_RESEARCH_COMPLETE                            = 0x0BF3, // 5.0.5 16048
    SMSG_RESEARCH_SETUP_HISTORY                       = 0x0BF1, // 5.0.5 16048
    SMSG_RESET_COMPRESSION_CONTEXT                    = 0,
    SMSG_RESET_FAILED_NOTIFY                          = 0,
    SMSG_RESISTLOG                                    = 0,
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                 = 0,
    SMSG_RESURRECT_REQUEST                            = 0,
    SMSG_RESYNC_RUNES                                 = 0,
    SMSG_ROLE_POLL_BEGIN                              = 0,
    SMSG_RWHOIS                                       = 0,
    SMSG_SELL_ITEM                                    = 0xC76,	// 5.0.5 16048
    SMSG_SEND_MAIL_RESULT                             = 0,
    SMSG_SEND_UNLEARN_SPELLS                          = 0xBB0,  // 5.0.5 16048
    SMSG_SERVERTIME                                   = 0x0999, // 5.0.5 16048
    SMSG_SERVER_FIRST_ACHIEVEMENT                     = 0,
    SMSG_SERVER_INFO_RESPONSE                         = 0x0A5C, // 5.0.5 16048
    SMSG_SERVER_MESSAGE                               = 0,
    SMSG_SERVER_PERF                                  = 0,
    SMSG_SETUP_RESEARCH_HISTORY                       = 0,
	SMSG_SET_AI_ANIM_KIT							  = 0,
    SMSG_SET_DF_FAST_LAUNCH_RESULT                    = 0,
    SMSG_SET_FACTION_ATWAR                            = 0x0DD2, // 5.0.5 16048
    SMSG_SET_FACTION_STANDING                         = 0,
    SMSG_SET_FACTION_VISIBLE                          = 0,
    SMSG_SET_FLAT_SPELL_MODIFIER                      = 0xC74,	// 5.0.5 16048
    SMSG_SET_FORCED_REACTIONS                         = 0xDE0,  // 5.0.5 16048
	SMSG_SET_MELEE_ANIM_KIT							  = 0,
	SMSG_SET_MOVEMENT_ANIM_KIT                        = 0,
    SMSG_SET_PCT_SPELL_MODIFIER                       = 0x802,	// 5.0.5 16048
    SMSG_SET_PHASE_SHIFT                              = 0x0A93, // 5.0.5 16048
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT             = 0,
    SMSG_SET_PLAY_HOVER_ANIM                          = 0,
    SMSG_SET_PROFICIENCY                              = 0x0823, // 5.0.5 16048
    SMSG_SET_PROJECTILE_POSITION                      = 0x08BC, // 5.0.5 16048
    SMSG_SHOWTAXINODES                                = 0,
    SMSG_SHOW_BANK                                    = 0,
    SMSG_SHOW_RATINGS                                 = 0x0B99, // 5.0.5 16048
    SMSG_SOR_START_EXPERIENCE_INCOMPLETE              = 0x0AB4, // 5.0.5 16048
    SMSG_SPELLBREAKLOG                                = 0xC45,	// 5.0.5 16048
    SMSG_SPELLDAMAGESHIELD                            = 0xDA5,	// 5.0.5 16048
    SMSG_SPELLDISPELLOG                               = 0x931,	// 5.0.5 16048
    SMSG_SPELLENERGIZELOG                             = 0x9C0,	// 5.0.5 16048
    SMSG_SPELLHEALLOG                                 = 0x890,	// 5.0.5 16048
    SMSG_SPELLINSTAKILLLOG                            = 0xC56,	// 5.0.5 16048
    SMSG_SPELLINTERRUPTLOG                            = 0xF8A,	// 5.0.5 16048
    SMSG_SPELLLOGEXECUTE                              = 0xC72,	// 5.0.5 16048
    SMSG_SPELLLOGMISS                                 = 0x854,	// 5.0.5 16048
    SMSG_SPELLNONMELEEDAMAGELOG                       = 0x9F4,	// 5.0.5 16048
    SMSG_SPELLORDAMAGE_IMMUNE                         = 0X977,	// 5.0.5 16048
    SMSG_SPELLSTEALLOG                                = 0xDAC,	// 5.0.5 16048
    SMSG_SPELL_CATEGORY_COOLDOWN                      = 0, //unused
    SMSG_SPELL_COOLDOWN                               = 0xD75,	// 5.0.5 16048
    SMSG_SPELL_DELAYED                                = 0xC17,	// 5.0.5 16048
    SMSG_SPELL_FAILED_OTHER                           = 0xC0E,	// 5.0.5 16048
    SMSG_SPELL_FAILURE                                = 0xD93,	// 5.0.5 16048
    SMSG_SPELL_GO                                     = 0xD42,	// 5.0.5 16048
    SMSG_SPELL_START                                  = 0x8FC,	// 5.0.5 16048
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                   = 0x858,	// 5.0.5 16048
    SMSG_SPIRIT_HEALER_CONFIRM                        = 0x0C7F, // 5.0.5 16048
    SMSG_SPLINE_MOVE_COLLISION_DISABLE                = 0,
    SMSG_SPLINE_MOVE_COLLISION_ENABLE                 = 0,
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE                  = 0,
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE                   = 0x0A56, // 5.0.5 16048
    SMSG_SPLINE_MOVE_ROOT                             = 0,
    SMSG_SPLINE_MOVE_SET_FEATHER_FALL                 = 0x0BD5, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_FLIGHT_BACK_SPEED            = 0,
    SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED                 = 0,
    SMSG_SPLINE_MOVE_SET_FLYING                       = 0,
    SMSG_SPLINE_MOVE_SET_HOVER                        = 0x0A90, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_LAND_WALK                    = 0x0A49, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_NORMAL_FALL                  = 0,
    SMSG_SPLINE_MOVE_SET_PITCH_RATE                   = 0,
    SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED               = 0x0A10, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_RUN_MODE                     = 0x0A9A, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_RUN_SPEED                    = 0x0A9C, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_SWIM_BACK_SPEED              = 0,
    SMSG_SPLINE_MOVE_SET_SWIM_SPEED                   = 0,
    SMSG_SPLINE_MOVE_SET_TURN_RATE                    = 0x0A44, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_WALK_MODE                    = 0x0A2C, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_WALK_SPEED                   = 0x0B8F, // 5.0.5 16048
    SMSG_SPLINE_MOVE_SET_WATER_WALK                   = 0,
    SMSG_SPLINE_MOVE_START_SWIM                       = 0,
    SMSG_SPLINE_MOVE_STOP_SWIM                        = 0,
    SMSG_SPLINE_MOVE_UNROOT                           = 0x0AAC, // 5.0.5 16048
    SMSG_SPLINE_MOVE_UNSET_FLYING                     = 0,
    SMSG_SPLINE_MOVE_UNSET_HOVER                      = 0x0BC0, // 5.0.5 16048
    SMSG_SPLINE_MOVE_WATER_WALK                       = 0x0B69, // 5.0.5 16048
    SMSG_STABLE_RESULT                                = 0,
    SMSG_STANDSTATE_UPDATE                            = 0x08BB, // 5.0.5 16048
    SMSG_START_MIRROR_TIMER                           = 0,
    SMSG_START_TIMER                                  = 0,
    SMSG_STOP_DANCE                                   = 0,
    SMSG_STOP_MIRROR_TIMER                            = 0,
    SMSG_STREAMING_MOVIE                              = 0x0B4C, // 5.0.5 16048
    SMSG_SUMMON_CANCEL                                = 0,
    SMSG_SUMMON_REQUEST                               = 0,
    SMSG_SUPERCEDED_SPELL                             = 0xA6B,
    SMSG_SUPPRESS_NPC_GREETINGS                       = 0x0A2A, // 5.0.5 16048
    SMSG_SUSPEND_COMMS                                = 0,
    SMSG_SUSPEND_TOKEN_RESPONSE                       = 0x0B4F, // 5.0.5 16048
    SMSG_TALENTS_ERROR                                = 0,
    SMSG_TALENTS_INFO                                 = 0,
    SMSG_TALENTS_INVOLUNTARILY_RESET                  = 0,
    SMSG_TAXINODE_STATUS                              = 0xDC4,	// 5.0.5 16048
    SMSG_TEST_DROP_RATE_RESULT                        = 0,
    SMSG_TEXT_EMOTE                                   = 0x0880, // 5.0.5 16048
    SMSG_THREAT_CLEAR                                 = 0xC9B,	// 5.0.5 16048
    SMSG_THREAT_REMOVE                                = 0x09BF, // 5.0.5 16048
    SMSG_THREAT_UPDATE                                = 0xDB0,	// 5.0.5 16048
    SMSG_TIME_ADJUSTMENT                              = 0,
    SMSG_TIME_SYNC_REQ                                = 0x0AA9, // 5.0.5 16048
    SMSG_TITLE_EARNED                                 = 0,
    SMSG_TOGGLE_XP_GAIN                               = 0x9E4,	// 5.0.5 16048
    SMSG_TOTEM_CREATED                                = 0,
    SMSG_TRADE_STATUS                                 = 0,
    SMSG_TRADE_STATUS_EXTENDED                        = 0x0AFB, // 5.0.5 16048
    SMSG_TRAINER_BUY_FAILED                           = 0,
    SMSG_TRAINER_BUY_RESULT                           = 0,
    SMSG_TRAINER_BUY_SUCCEEDED                        = 0,
    SMSG_TRAINER_LIST                                 = 0,
    SMSG_TRANSFER_ABORTED                             = 0,
    SMSG_TRANSFER_PENDING                             = 0,
    SMSG_TRIGGER_CINEMATIC                            = 0xC18,  // 5.0.5 16048
    SMSG_TRIGGER_MOVIE                                = 0xD51,  // 5.0.5 16048
    SMSG_TURN_IN_PETITION_RESULTS                     = 0,
    SMSG_TUTORIAL_FLAGS                               = 0x8AE,  // 5.0.5 16048
    SMSG_UNIT_HEALTH_FREQUENT                         = 0,
    SMSG_UNIT_SPELLCAST_START                         = 0xC12,	// 5.0.5 16048
    SMSG_UPDATE_ACCOUNT_DATA                          = 0x860,	// 5.0.5 16048
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                 = 0,
    SMSG_UPDATE_COMBO_POINTS                          = 0,
    SMSG_UPDATE_CURRENCY                              = 0,
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                   = 0x0AEA, // 5.0.5 16048
    SMSG_UPDATE_DUNGEON_ENCOUNTER_FOR_LOOT            = 0x0A53, // 5.0.5 16048
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT               = 0,
    SMSG_UPDATE_INSTANCE_OWNERSHIP                    = 0x0C8C, // 5.0.5 16048
    SMSG_UPDATE_ITEM_ENCHANTMENTS                     = 0,
    SMSG_UPDATE_LAST_INSTANCE                         = 0,
    SMSG_UPDATE_OBJECT                                = 0x8F7,  // 5.0.5 16048
    SMSG_UPDATE_SERVER_PLAYER_POSITION                = 0,
    SMSG_UPDATE_WORLD_STATE                           = 0x847,	// 5.0.5 16048
    SMSG_USERLIST_ADD                                 = 0,
    SMSG_USERLIST_REMOVE                              = 0,
    SMSG_USERLIST_UPDATE                              = 0x095A, // 5.0.5 16048
    SMSG_VOICESESSION_FULL                            = 0,
    SMSG_VOICE_CHAT_STATUS                            = 0x09EE, // 5.0.5 16048
    SMSG_VOICE_PARENTAL_CONTROLS                      = 0x0CF0, // 5.0.5 16048
    SMSG_VOICE_SESSION_LEAVE                          = 0x085D, // 5.0.5 16048
    SMSG_VOICE_SESSION_ROSTER_UPDATE                  = 0,
    SMSG_VOICE_SET_TALKER_MUTED                       = 0x097B, // 5.0.5 16048
    SMSG_VOID_ITEM_SWAP_RESPONSE                      = 0,
    SMSG_VOID_STORAGE_CONTENTS                        = 0,
    SMSG_VOID_STORAGE_FAILED                          = 0,
    SMSG_VOID_STORAGE_TRANSFER_CHANGES                = 0x0BD9, // 5.0.5 16048
    SMSG_VOID_TRANSFER_RESULT                         = 0,
    SMSG_WAIT_QUEUE_FINISH                            = 0,
    SMSG_WAIT_QUEUE_UPDATE                            = 0x0AC8, // 5.0.5 16048
    SMSG_WARDEN_DATA                                  = 0,
    SMSG_WARGAME_CHECK_ENTRY                          = 0x0BE6, // 5.0.5 16048
    SMSG_WARGAME_REQUEST_SENT                         = 0,
    SMSG_WEATHER                                      = 0x814,	// 5.0.5 16048
    SMSG_WEEKLY_LAST_RESET                            = 0x0B2D, // 5.0.5 16048
    SMSG_WEEKLY_RESET_CURRENCY                        = 0,
    SMSG_WEEKLY_SPELL_USAGE                           = 0x0B6D, // 5.0.5 16048 //unused
    SMSG_WEEKLY_SPELL_USAGE_UPDATE                    = 0x0B6D, // 5.0.5 16048 //unused
    SMSG_WHO                                          = 0x933,	// 5.0.5 16048
    SMSG_WHOIS                                        = 0x0943, // 5.0.5 16048
    SMSG_WORLD_SERVER_INFO                            = 0x0A6D, // 5.0.5 16048
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                  = 0xD83,	// 5.0.5 16048
    SMSG_XP_GAIN_ABORTED                              = 0x0B76, // 5.0.5 16048
    SMSG_ZONE_UNDER_ATTACK                            = 0,
};

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player != NULL or _player == NULL && m_playerRecentlyLogout && m_playerLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;
class WorldSession;

typedef void(WorldSession::*pOpcodeHandler)(WorldPacket& recvPacket);

struct OpcodeHandler
{
    OpcodeHandler() {}
    OpcodeHandler(char const* _name, SessionStatus _status, PacketProcessing _processing, pOpcodeHandler _handler)
        : name(_name), status(_status), packetProcessing(_processing), handler(_handler) {}

    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    pOpcodeHandler handler;
};

extern OpcodeHandler* opcodeTable[NUM_OPCODE_HANDLERS];
void InitOpcodes();

/// Lookup opcode name for human understandable logging
inline std::string GetOpcodeNameForLogging(Opcodes id)
{
    uint32 opcode = uint32(id);
    std::ostringstream ss;
    ss << '[';

    if (id < UNKNOWN_OPCODE)
    {
        if (OpcodeHandler* handler = opcodeTable[uint32(id) & 0x7FFF])
        {
            ss << handler->name;
            if (opcode & COMPRESSED_OPCODE_MASK)
                ss << "_COMPRESSED";
        }
        else
            ss << "UNKNOWN OPCODE";
    }
    else
        ss << "INVALID OPCODE";

    ss << " 0x" << std::hex << std::uppercase << opcode << std::nouppercase << " (" << std::dec << opcode << ")]";
    return ss.str();
}

#endif
/// @}
